### ISSUE TITLE
Выбор иконки для объекта для диаграммы

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#101]
на главной странице платформы при клике на аватарку всплывает окно с иконками.
Иконки не понятно для чего и при выборе не возможно найти отображение.

https://user-images.githubusercontent.com/113026498/194875824-b1300806-5426-4231-b8b6-9f1491ea67b8.mov

**Comment by hope4b** [comment]
a7bf8a6a Artem Varkulevich <artem.varkulevich@gmail.com> on 04.11.2022 at 14:27
