### ISSUE TITLE
Вкладка поиск объекта

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#114]
1. Открыть платформу Онто
2. Открыть диаграмму
3. Кликнуть на "Открыть пространство"

В поисковом окне исправить плейсхолдер с "Начните вводить название ш..." на "Начните вводить".
![Как сбросить поиск](https://user-images.githubusercontent.com/113026498/202106052-34757170-eb20-43ba-9b18-cb0276add1c4.png)

**Comment by hope4b** [comment]
placeholder="Начнем"

cdfc94a4 Artem Varkulevich <artem.varkulevich@gmail.com> on 24.11.2022 at 0:26
