### ISSUE TITLE
Вкладка шаблоны

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#115]
1. Открыть платформу Онто
2. Открыть диаграмму
3. Кликнуть на "Открыть пространство"

Вкладка "Шаблоны" не кликабельна на сегодняшний момент, но в разработке. Во избежание недопонимания со стороны пользователя предлагаю на клике на шаблон сделать всплывающее сообщение "функция уже в разработке" или что-то на подобии.
![Вкладка Шаблоны](https://user-images.githubusercontent.com/113026498/202108567-95ebb69c-a744-4b62-b818-d8e10cd87aad.png)
Пример:
![Информационное всплывающее окно](https://user-images.githubusercontent.com/113026498/202108599-edc71f50-fffe-4a7a-8db9-fe39a45f4b25.png)

**Comment by vamukhin** [comment]
убрал "Шаблоны"

**Comment by SmirnovaChristina** [comment]
Реализовано
