### ISSUE TITLE
Список связей

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#116]
1. Открыть платформу Онто
2. Открыть диаграмму
3. Кликнуть на "Открыть пространство"
4. Выбрать диаграмму
6. Кликнуть на "Открыть карточку объекта"

Я выбираю на диаграмме объект "Пространство", открывается правая панель, в сайдбаре "Связи", **я вижу связи с объектом**, но если я открываю "карточку объекта" (клик на иконку/кнопку), то во вкладке "Список связей" **пусто**. Почему?

![Связи](https://user-images.githubusercontent.com/113026498/202110426-e2fd4e13-93ed-42ef-9c7f-d805ed223620.png)

![Список связей](https://user-images.githubusercontent.com/113026498/202110448-323dad0f-f150-4845-b2a1-442a9c0bed81.png)

**Comment by hope4b** [comment]
этот функционал еще не сделан. Займусь им

**Comment by SmirnovaChristina** [comment]
Не актуально. Карточка "Объекты" вынесена с диаграммы. Связи отображаются.
