### ISSUE TITLE
Поиск чувствителен к регистру

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#12]
При добавлении нового элемента на диаграмму, поиск чувствителен к регистру, поиск по слову "стратегия" не находит "Стратегия"
![image](https://user-images.githubusercontent.com/94846908/144417860-5e2d8aea-9bd8-4f1f-803b-db6fde6d2a95.png)

**Comment by AndreyDobrichenko** [comment]
При изменении metaEntity поиск чувствителен к регистру только для русского языка, для английского работает нормально.
![image](https://user-images.githubusercontent.com/94846908/144430429-29708245-c8be-45d8-a627-019bdcdda008.png)

**Comment by AndreyDobrichenko** [comment]
актуально

**Comment by AndreyDobrichenko** [comment]
актуально

**Comment by hope4b** [comment]
объекты ищутся без контроля регистра. Поиск классов актуально

**Comment by AndreyDobrichenko** [comment]
не актуально
