### ISSUE TITLE
При удалении шаблона, стикеры для которых был задан этот шаблон, остаются объектами.

### ISSUE THREAD

**Issue by AlexanderShaleins** [hope4b/onto#120]
https://user-images.githubusercontent.com/105632547/205659012-746f1e95-bcd9-4319-8470-c7586d093c75.mp4

**Comment by AndreyDobrichenko** [comment]
Такому стикеру-объекту не получается сбросить шаблон на правой панели (на диаграмме).

**Comment by vamukhin** [comment]
сначала на бэк

**Comment by hope4b** [comment]
Почему на бек? Представление определяет бек, то что бек прислал то что это представление обьект это нормально.

**Comment by rosalieuru** [comment]
связано с  #185, будет нельзя удалять шаблоны, у которых есть экземпляры 
после реализации закроем

**Comment by rosalieuru** [comment]
Добавлено ограничение на удаление шаблона, у которого есть экземпляры
