### ISSUE TITLE
Не хватает функции удаления объекта 

### ISSUE THREAD

**Issue by AlexanderShaleins** [hope4b/onto#123]
Можно быстро создать много объектов. А удалить нельзя никак. 
![image](https://user-images.githubusercontent.com/105632547/205667577-df2e1af3-b4a1-4e33-8072-6630b2ec8edf.png)

**Comment by AndreyDobrichenko** [comment]
Поддерживаю, не хватает. Делаешь предметную область, добавил лишнюю связь между объектами, а удалить нельзя.

**Comment by SmirnovaChristina** [comment]
24.02 кнопка работает.

**Comment by SmirnovaChristina** [comment]
Не удаётся с концами удалить объекты.
При удалении объекта/ов через инструмент карточка "Объекты" на диаграмме остаются бледная тень удалённого объекта/ов, но без имени. При этом объекты удаляются из карточки.
![Снимок экрана 2023-03-01 085637](https://user-images.githubusercontent.com/113026498/222070334-7430d13b-de18-4a1c-bcb6-805593ae1094.png)

**Comment by SmirnovaChristina** [comment]
Удаление работает. Объекты не остаются. 10.03
