### ISSUE TITLE
Наименование пространства

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#125]
1. Открыть платформу Онто
2. Кликнуть на созданное пространство (или на создание нового пространства)

Сейчас чтобы внести наименование созданного пространства или внести изменение в наименование ранее созданного пространства необходимо сначала навести курсор.
Необходимо предусмотреть автоматический ввод.

https://user-images.githubusercontent.com/113026498/207844153-8c7bd5f2-aec1-4cb3-9939-0ae18c260d2a.mp4

**Comment by AndreyDobrichenko** [comment]
Сейчас вообще нет кнопок редактирования наименования пространства:
![image](https://user-images.githubusercontent.com/94846908/209070936-5a35693d-f997-4870-9871-7eed92bc74a1.png)

**Comment by AndreyDobrichenko** [comment]
Кнопки появились. Ишью актуальна.

**Comment by rosalieuru** [comment]
Оба бага не воспроизводятся.
