### ISSUE TITLE
Плейсхолдер для имени диаграммы

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#130]
1. Открыть платформу Онто
2.  Создать новую диаграмму
3. Перейти в левом верхнем углу на имя «Новая диаграмма»

Сейчас чтобы внести имя новой диаграммы надо навести курсор на поле "Новая диаграмма", кликнуть 2 раза, удалить или сразу внести новое имя. Это сложно. Надо подумать как сделать ввод быстрее.
Возможно ли сделать плейсхолдер? К примеру, как полем ниже, там где можно внести описание.

https://user-images.githubusercontent.com/113026498/213267931-8ae3d65d-b60a-44be-8d56-651a9e33f145.mp4

**Comment by AndreyDobrichenko** [comment]
> `Сейчас чтобы внести имя новой диаграммы надо навести курсор на поле "Новая диаграмма", кликнуть 2 раза, удалить или сразу внести новое имя.`
Открывается по одному клику.

**Comment by SmirnovaChristina** [comment]
Не актуально есть фокус
