### ISSUE TITLE
Выход из окна

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#131]
1. Открыть платформу Онто
2. Создать новую диаграмму
3. Перейти в левом верхнем углу на имя «Новая диаграмма»

Открывается окно, в котором можно внести имя диаграммы и дать ей описание.
Чтобы выйти из окна пользователю необходимо нажать кнопку "отмена", это не удобно, пользователь теряет скорость работы.
Есть ли возможность предусмотреть выход путём клика по странице? Или быстрой клавишей? Или и то и другое?

https://user-images.githubusercontent.com/113026498/213270609-654c2cbc-f7b0-45be-900f-4e8558662ea2.mp4

**Comment by SmirnovaChristina** [comment]
Надо пересмотреть все окна

**Comment by Cracer00** [comment]
Добавлена возможность закрывать диалоговое окно по клику вне диалогового окна в следующих окнах:
1. Окно переименования диаграммы.
2. Окно переименования пространства.
3. Окно "Учебный центр".
4. Окно "Поделиться пространством".

**Comment by rosalieuru** [comment]
Дополнение бага: 
модульные окна не закрываются при переходе "назад" в браузере

**Comment by Cracer00** [comment]
Добавлены кнопки закрывающие модальное окно в следующие окна. Выкатил на пре-прод
1. Окно "Поделиться пространством"
2. Окно "Изменить название пространства"
3. Окно "О диаграмме"

**Comment by rosalieuru** [comment]
В работу также взяли модалку на создание нового пространства. 
Текущие проблемы: автофокус пропадает после закрытия модалки, отсутствует крестик, не закрывается кликом out of form, рамка поля ввода отличается по цвету от других

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/265
