### ISSUE TITLE
Имя диаграммы пустое поле

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#132]
1. Открыть платформу Онто
2. Создать новую диаграмму
3. Перейти в левом верхнем углу на имя «Новая диаграмма»

Открывается окно, в котором можно внести имя диаграммы и дать ей описание.
Форма даёт изменить поле имени на пустое. При этом покинув окно нажав кнопку "Изменить" имя диаграммы будет пустым, но пользователь не сможет вновь перейти в окно "имени" и повторно внести изменения имени. Форма не даёт.
И назад откатиться форма не позволяет.
Для того чтоб внести изменения пользователю необходимо вернуться в пространство и заново зайти в диаграмму.

Какой должен быть результат? Какие требования к содержимому поля? Возможно стоит запретить пустое поле или пробелы.
Как вернуться на шаг назад?

https://user-images.githubusercontent.com/113026498/213272653-4679346d-2822-4e2e-870b-1a694021ea89.mp4

**Comment by rosalieuru** [comment]
fixed
