### ISSUE TITLE
Поле описания диаграммы

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#133]
1. Открыть платформу Онто
2. Создать новую диаграмму
3. Перейти в левом верхнем углу на имя «Новая диаграмма»

Открывается окно, в котором можно внести имя диаграммы и дать ей описание.
Какие требования к полю? Где отражается информация с описанием?
Сейчас можно внести более 250 букв/символов, при этом поле не увеличивается, то есть просмотреть текст целиком невозможно.
Возможно имеет смысл предусмотреть требования к количеству вводимых букв и символов или предусмотреть увеличение поля в зависимости от количества вводимых букв/символов/чисел.

https://user-images.githubusercontent.com/113026498/213275006-1a147a3a-27e9-41a6-b502-b3b4b5304373.mp4

**Comment by AndreyDobrichenko** [comment]
Тоже самое применимо к полю Имя, только длина введенного текста влияет на отображение в общем списке диаграмм:
![image](https://user-images.githubusercontent.com/94846908/214260524-ac87f401-3281-4b26-887c-4ac182e9d24b.png)

**Comment by rosalieuru** [comment]
Актуализация: 
на данный момент стоит ограничение на вывод 2 строк

В работе: изменить на 3 строки
