### ISSUE TITLE
Следы выравнивания

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#139]
На диаграмме, после того как подвигал объект и выровнял его положение относительно другого объекта, пунктирная линия остается.
![image](https://user-images.githubusercontent.com/94846908/215090620-a4dce78b-cafa-4db4-9cb1-a6dfcccf49cb.png)

**Comment by SmirnovaChristina** [comment]
Остаётся след выравнивания после скрытия стикеров

![Снимок экрана 2023-03-01 090504](https://user-images.githubusercontent.com/113026498/222064064-db79a055-90dd-4685-bce0-dc238707347f.png)

**Comment by SmirnovaChristina** [comment]
При изменении объекта на стикер и наоборот остаётся след выравнивания
![Снимок экрана 2023-02-28 131155](https://user-images.githubusercontent.com/113026498/222065306-6468072a-749e-4138-9215-a842095aa496.png)

**Comment by AndreyDobrichenko** [comment]
не актуально
