### ISSUE TITLE
Изменение направления связи меняется только после перезагрузки диаграммы

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#143]
1. Зайти на диаграмму.
2. Кликнуть на связь на диаграмме.
3. На правой панели нажать иконку "Сменить"
4. Ничего не происходит.
5. Обновить диаграмму.
6. Видим что направление стрелки изменилось.
<img width="458" alt="Снимок экрана 2023-02-09 в 16 56 33" src="https://user-images.githubusercontent.com/94846908/217832654-aff9cd16-d0a2-42be-ac9a-5ba52d439056.png">

**Comment by SmirnovaChristina** [comment]
01/03 стрелка меняет направление
