### ISSUE TITLE
Диаграмма / Редактировать имя свойства объекта можно только сразу и пока активно окно

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#144]
1. Заходим на диаграмму.
2. Кликаем на объект.
3. На правой панели добавляем свойства объекту.
4. Можем редактировать Имя и Значение у всех свойств которые добавили.
5. Переводим фокус с правой панели - кликаем на диаграмму или другой объект.
6. Кликаем на объект которому добавляли свойства.
7. Можем изменить Значение, но не можем изменить Имя свойства.

Хотелось бы всегда иметь возможность изменить Имя свойства, сейчас можно в момент создания и до того как переключишся на другой объект, при возвращении к первому объекту изменить Имя свойства уже нельзя.

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/174
