### ISSUE TITLE
Нельзя вернуть цвет по умолчанию

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#153]
В инструменте Карточка Объекты и на диаграмме, если поменять цвет, то уже нельзя вернуть цвет по умолчанию.
Хочется. Иметь опцию в инструменте выбора цвета, позволяющую сбросить изменения цвета элемента. Если это стикер, то что бы цвет становился цветом по умолчанию, как при создании. Если это объект, то что бы цвет объекта становился цветом из шаблона.

**Comment by SmirnovaChristina** [comment]
Есть такая возможность.
