### ISSUE TITLE
при восстановлении связи не восстанавливаются типы связей

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#154]
Все связи объекта ОТР типизированы

![image_2023-02-22_21-41-07](https://user-images.githubusercontent.com/47814520/220727339-68e6594f-cbbd-4e6f-8086-f3642fe11fb5.png)

но при этом при восстановлении связи из сайдбара тип связи не восстанавливается
![image_2023-02-22_21-41-21](https://user-images.githubusercontent.com/47814520/220727866-2014b241-7310-483e-ac12-f91d0fed9fe7.png)

**Comment by AndreyDobrichenko** [comment]
заработало
