### ISSUE TITLE
Визуально не изменяется направление стрелки при изменении направления связи

### ISSUE THREAD

**Issue by IrinaPustygina** [hope4b/onto#155]
Когда хочешь поменять направление связи от одного шаблона к другому, направление наконечника стрелки не изменяется. 
Связь направление меняет, а визуально этого не видно. 

<img width="1219" alt="Снимок экрана 2023-02-25 в 14 11 42" src="https://user-images.githubusercontent.com/116802158/221353828-6ca71b56-f050-4efc-a763-34cfa1490def.png">
<img width="1238" alt="Снимок экрана 2023-02-25 в 14 11 51" src="https://user-images.githubusercontent.com/116802158/221353830-9f1d568b-7eec-451c-a915-049e0d80b8d5.png">

**Comment by SmirnovaChristina** [comment]
Направление меняется только после перезагрузки.
Задачу закрываю, бег зарегистрирован #143
