### ISSUE TITLE
Инструкция. добавить пункты

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#16]
Нет описания фичи "Добавление класса".
Нет описания фичи "быстрое удаление связи"

**Comment by AndreyDobrichenko** [comment]
Добавил пункт Класс (создание).
Отредактировал пункт Связи на диаграмме (удаление связи).
Поправил инструкцию в соответствии с опубликованным вариантом на сайте.
[Инструкция пользователя.docx](https://github.com/hope4b/onto/files/7744380/default.docx)
