### ISSUE TITLE
Диаграмма / Служебный класс показывается в шаблонах

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#160]
Диаграмма
Сайдбар
Задать шаблон

На английской раскладке вылезает неизвестный шаблон "SYS_REALM_USER_ROLE".
![Снимок экрана 2023-03-01 092420](https://user-images.githubusercontent.com/113026498/222063685-bb6b6200-83d3-4266-81d3-f09f1769a847.png)

**Comment by hope4b** [comment]
https://ontonet.online/api/v2/core/realm/***/diagram/v2/8df2cb7e-af98-4863-be29-9222f050b058/all_nodes/filtered?ontoNodeOrClassName=e

**Comment by hope4b** [comment]
Здесь неправильный метод используется. Нужно заменить на графкуэль

**Comment by hope4b** [comment]
@rosalieuru  это хорошая задача для Ивана @Cracer00 будет со временем

**Comment by hope4b** [comment]
{
  metaEntity(
    filter: {
      realm: {
        uuid: "**************"       
      } AND :
      {
        realm_not: null
      }
    }
    first: 100
    offset: 0
    orderBy: [uuid_asc]
  ) {
    uuid
    name
    describer {
      fields {
        name
        value
      }
    }
  }
}


{
  "data": {
    "metaEntity": [
      {
        "name": "[DEV] в работе",
        "describer": {
          "fields": [
            {
              "name": "repColor",
              "value": "#ff9417"
            },
            {
              "name": "objicon",
              "value": "https://cdn-icons-png.flaticon.com/64/49/49728.png"
            }
          ]
        },
        "uuid": "00431f42-d796-4ce7-a7ca-4808c90b0839"
      },
      {
        "name": "[DEV] Эпик",
        "describer": {
          "fields": [
            {
              "name": "repColor",
              "value": "#a4c6ff"
            },
            {
              "name": "objicon",
              "value": "objico/lib/flaticons/4558072-office/061-badge"
            }
          ]
        },
        "uuid": "009fcc45-c117-416d-88d9-e4a8ec38839d"
      },

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-core/pull/481

**Comment by hope4b** [comment]
На тест
