### ISSUE TITLE
При первой попытке изменить название диаграммы - старое окно

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#163]
1. В новом окне браузера открываем онто
2. Заходим на диаграмму
3. Кликаем на название диаграммы, что бы поменять название
4. Видим старое окно, в котором нет кнопок и нельзя применить изменения
5. Нажимаем ESC
6. Можем повторять шаги 3, 4, 5 до бесконечности
7. Нажимаем F5
8. Кликаем на название диаграммы - видим новое окно с кнопками

Старое окно:
![image](https://user-images.githubusercontent.com/94846908/222204247-af08f9b3-25f9-4450-a4df-d730963658c0.png)

Новое окно:
![image](https://user-images.githubusercontent.com/94846908/222205927-286a65f5-ee74-4a7c-ac27-6df675497285.png)

Видео:

https://user-images.githubusercontent.com/94846908/222206826-c90b575a-2205-44d1-a4f9-d3fc89981d4a.mov

**Comment by AndreyDobrichenko** [comment]
не во всех браузерах

**Comment by rosalieuru** [comment]
с окнами все ок, добавили закрытие кликом out of form
