### ISSUE TITLE
При повторном добавлении объекта из шаблонов на диаграмму сбрасывается цвет, установленный по умолчанию.

### ISSUE THREAD

**Issue by IrinaPustygina** [hope4b/onto#164]
1. Вытаскиваем объект из шаблонов на диаграмму, он вытаскивается в установленном по умолчанию цвете.
2. Удаляем этот объект с диаграммы.
3. Снова вытаскиваем тот же самый объект на ту же самую диаграмму, он появляется в желтом цвете, даже если установлен по умолчанию другой 
4.  При перезагрузке страницы цвет объекта  подтягивается из шаблона.

**Comment by vamukhin** [comment]
известный баг на бэкенд

**Comment by AndreyDobrichenko** [comment]
заработало
