### ISSUE TITLE
Работа с цветом элементов

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#166]
Ожидаемая работа с цветом: 

- вручную установленный цвет для элемента на диаграмме имеет высший приоритет
- цвет из шаблона уступает вручную установленному, но заменяет цвет по умолчанию
- через палитру инструмента "Задать цвет" можно отменить вручную установленный цвет
- элементы вытаскиваемые на диаграмму из пространства не могут иметь вручную установленного цвета, либо по умолчанию либо из шаблона

1. Стикер.
1.1. Работает. При создании нового стикера на диаграмме ему устанавливается цвет по умолчанию (желтый).
1.2. Работает. При изменении цвета стикера на диаграмме через инструмент "Задать цвет" на сайдбаре - ему устанавливается выбранный в палитре цвет.
1.2.1. **Баг.** Если не закрыть сайдбар не переключаться на другие элементы и обновить диаграмму, то выбранный в палитре цвет сбросится на цвет по умолчанию.
1.3. **Надо делать.** Я как пользователь, находясь на диаграмме, могу выбранному стикеру через инструмент "Задать цвет" на сайдбаре, вернуть цвет по умолчанию для стикеров. 
На палитре инструмента "Задать цвет" нужна опция сбросить установленный цвет. При ее выборе у стикера сбрасывается цвет на цвет по умолчанию.
![image](https://user-images.githubusercontent.com/94846908/222501764-8c7a6f0e-2014-40b2-9e9e-e70c11c80655.png)
1.3.1. Можно заморочиться и делать эту опцию на палитре не активной, если у стикера уже установлен цвет по умолчанию.
2. Стикер -> Объект.
2.1. Работает. Стикер имел цвет по умолчанию, к нему применяется шаблон в котором цвет по умолчанию - получаем объект с цветом по умолчанию.
2.2. Стикер имел цвет по умолчанию, к нему применяется шаблон с предустановленным цветом:
2.2.1. Ожидаемое поведение. Выбранный стикер преобразуется в объект, его цвет становится цветом из шаблона.
2.2.2. **Баг.** Реальное поведение. Выбранный стикер преобразуется в объект, его цвет остается цветом по умолчанию (желтым).
2.2.2.1. Лайвхак. Если сайдбар был свернут или выбрать другой элемент на диаграмме и обновить диаграмму, то у объекта цвет станет цветом из шаблона. 
2.2.2.2. **Баг.** Если сайдбар оставить развернутым и обновить диаграмму, то объект станет стикером с цветом по умолчанию (желтым).
2.3. Работает. Стикер имел измененный цвет, к нему применяется шаблон в котором цвет по умолчанию (не выбирался) - получаем объект с измененным цветом, который был у стикера.
2.4. Стикер имел измененный цвет, к нему применяется шаблон в котором предустановлен цвет:
2.4.1. Ожидаемое поведение. Выбранный стикер преобразуется в объект, его цвет остается с цветом стикера. 
3. Работает. Размещенный из пространства на диаграмму стикер имеет цвет по умолчанию.
4. Работает. Размещенный из пространства на диаграмму объект имеет цвет из шаблона.
5. Объект -> Стикер.
5.1. Объект имел цвет из шаблона, у него удаляется шаблон на сайдбаре.
5.1.1. Ожидаемое поведение. Выбранный объект преобразуется в стикер, его цвет становится цветом по умолчанию (желтым).
5.1.2. **Баг.** Реальное поведение. Выбранный объект преобразуется в стикер, его цвет остается предустановленным цветом из шаблона, который был у объекта.
5.1.2.1. **Баг.** Если сайдбар оставить развернутым не переключаться на другие элементы и обновить диаграмму, то стикер станет объектом.
5.2. Объект имел цвет по умолчанию (не было шаблонного цвета), у него удаляется шаблон.
5.2.1. Работает. Ожидаемое поведение. Выбранный объект преобразуется в стикер, его цвет остается цветом по умолчанию.
5.2.1.1 **Баг.** Если сайдбар оставить развернутым не переключаться на другие элементы и обновить диаграмму, то стикер станет объектом.
6. Объект -> Объект.
6.1. Работает. Объект_1 имел цвет по умолчанию из шаблона_1 (в шаблоне_1 не был выбран цвет), к этому объекту_1 применяется другой шаблон_2 (в шаблоне_2 не был выбран цвет) - к объекту_1 применяется шаблон_2, цвет применяется из шаблона_2, т.е. остается без изменений по умолчанию (желтый).
6.1.1. **Баг.** Не обновляя диаграмму перевыбирать объекты на диаграмме, если выбирать объект_1, то видим шаблон_2, убираем выделение с объекта_1, видим иконку шаблона_1.
6.1.2. **Баг.** "Не закрытый сайдбар" - аналогично багам выше, не сохраняется изменение при обновлении.
6.2. Объект имел цвет из шаблона_1 (цвет не выбран), к объекту применяется шаблон_2 с предустановленным цветом 
6.2.1. Ожидаемое поведение. К объекту применяется шаблон_2, устанавливается предустановленный цвет из шаблона_2.
6.2.2. **Баг.** Реальное поведение. У объекта пропадает иконка (должна быть из шаблона_2, цвет остается цветом по умолчанию (должен быть предустановленный цвет из шаблона_2).
6.2.3. **Баг.** Если снять выделение с объекта, а затем выделить его, то видим правильную иконку из шаблона_2 и правильный предустановленный цвет из шаблона_2. При снятии выделения с объекта нет иконки нет цвета.
6.2.4. Лайвхак. После обновления диаграммы иконка и цвет объекта становятся правильными из шаблона_2.
6.3. Объект имел предустановленный цвет_1 из шаблона_1, к нему применяется шаблон_2 без предустановленного цвета.
6.3.1. Ожидаемое поведение. К объекту применяется шаблон_2, цвет объекта становится по умолчанию (желтым).
6.3.2. **Баг.** Реальное поведение. Визуально ничего не происходит, иконка и цвет остались из шаблона_1.
6.3.3. **Баг.** Перевыделение объекта меняет иконку со старой на новую, цвет остается цветом_1.
6.3.4. **Баг.** Обновление диаграммы приводит к закреплению иконки_2 и цвету_1 (должно быть иконка_2, цвет по умолчанию (желтый).
6.4. Объект имел предустановленный цвет_1 из шаблона_1, к нему применяется шаблон_2 с предустановленным цветом_2.
6.4.1. Ожидаемое поведение. К объекту применяется шаблон_2, цвет объекта становится цветом_2.
6.4.2. **Баг.** Реальное поведение. Иконка пропадает (должна была стать иконкой из шаблона_2), цвет остается цветом_1 (должен стать цветом_2).
6.4.3. **Баг.** Не обновляя диаграмму, снять выделение с объекта, затем выбрать объект - при выделении показывает иконку из шаблона_2, цвет остается цветом_1.
6.4.4. **Баг.** Обновление диаграммы не помогает, иконка_2 закрепляется, но цвет остается цветом_1.
6.5. Объект имел вручную установленный цвет_ручной и шаблон_1, к нему применяется шаблон_2 с цветом_2.
6.5.1. Работает. Ожидаемое поведение. У объекта остается цвет_ручной.
6.6. Объект имел вручную установленный цвет_ручной и шаблон_1, к нему применяется шаблон_2 с цветом по умолчанию (цвет в шаблоне не выбран).
6.6.1. Работает. Ожидаемое поведение. У объекта остается цвет_ручной.
7. Шаблон.
7.1. В шаблоне_1 меняем цвет_1 (в том числе и цвет по умолчанию) на цвет_2.
7.1.1. Ожидаемое поведение. У объектов с цветом из шаблона_1, цвет_1 меняется на цвет_2. У объектов с шаблоном_1 и вручную установленным цвет_ручной - цвет остается цвет_ручной.
 7.1.1.1. Реальное поведение. На диаграмме объект имел цвет из шаблона цвет_1 - после обновления диаграммы, объект меняет цвет_1 на цвет_2.  На диаграмме объект имел цвет_ручной и шаблон_1 - после обновления диаграммы у объекта остается цвет_ручной.
8. Удаление шаблона_1 имеющего объекты.
8.1. У объекта на диаграмме имеющего шаблон_1 и шаблонный цвет_1 удалили шаблон_1.
8.1.1. Ожидаемое поведение. Объект превращается в стикер с цветом по умолчанию (желтым).
8.1.2. **Баг.** Реальное поведение. Ничего не происходит. Если обновить диаграмму, то объект теряет иконку и цвет из шаблона, но визуально остается объектом. При этом если объект в фокусе, то на сайдбаре видно, что у него нет шаблона, а точки привязки стрелок смещаются так, как будто это стикер. Если снять выделение с объекта, точки привязки стрелок как к объекту. Если изменить текст объекта, то при закрытии сайдбара, объект становится стикером.
8.2. У объекта на диаграмме имеющего шаблон_1 и ручной цвет - удалили шаблон_1.
8.2.1. Ожидаемое поведение. Объект превращается в стикер, ручной цвет остается.
8.2.2. **Баг.** Реальное поведение. Ничего не происходит. Если обновить диаграмму, то объект теряет иконку, цвет остается ручной, но визуально остается объектом.  При этом если объект в фокусе, то на сайдбаре видно, что у него нет шаблона, а точки привязки стрелок смещаются так, как будто это стикер. Если снять выделение с объекта, точки привязки стрелок как к объекту. Если изменить текст объекта, то при закрытии сайдбара, объект становится стикером.

**Comment by rosalieuru** [comment]
требования по работе с цветом вынесены в вики, указанные баги либо неактуальны либо вынесены в отдельные ишью
