### ISSUE TITLE
Работа кнопки Удалить объект в "Карточке"

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#167]
1. Кнопка "Удалить объект" всегда доступна к нажатию.
2. При нажатии Кнопки "Удалить объект", когда у объекта есть связи в Списке связей, выводить окно с информированием (текст подготавливается), что удалить объект нельзя пока есть связи. 
2.1. Есть только кнопка Ок в информационном окне, которая закрывает его.
2.2. ESC - закрывает информационное окно.
2.3. Клик мышью мима окна - закрывает информационное окно.
3. При нажатии Кнопки, если у объекта нет связей в Списке связей, выводить окно с предупреждением (текст подготавливается), что при удалении пропадет объект из пространства и все экземпляры объекта на диаграммах где он присутствовал. На выбор две кнопки "Удалить" и "Отмена".
3.1. Выбор кнопки "удалить" - удаляем объект из пространства и все экземпляры с диаграмм.
3.2. Выбор кнопки "Отмена" - закрывает предупреждающее окно. 
3.3. ESC - закрывает предупреждающее окно.
3.4. Клик мышью мимо окна - закрывает предупреждающее окно.

**Comment by SmirnovaChristina** [comment]
#2 "Удаление невозможно, объект имеет связи. Удалите связи в списке связей и вернитесь для удаления объекта".

#3 "Внимание!!! Действие приведет к безвозвратному удалению объекта из пространства Онто, в том числе и со всех диаграмм где он присутствует"
Кнопки "Удалить" и "Отмена".

**Comment by AndreyDobrichenko** [comment]
Можем сделать как в задаче написано? Не показывать всегда этот текст?
![image](https://user-images.githubusercontent.com/94846908/224364451-10859021-43c5-4990-a231-7a765d57c76b.png)

**Comment by AndreyDobrichenko** [comment]
Можем сделать обычное окно при нажатии кнопки "Удалить объект"?
![image](https://user-images.githubusercontent.com/94846908/224365079-46a23848-7c2f-41e2-99b0-2a069d62c008.png)

**Comment by AndreyDobrichenko** [comment]
Пропустили запятую и точку.
Было:
"Внимание!!! Действие приведет к безвозвратному удалению объекта из пространства Онто, в том числе и со всех диаграмм где он присутствует"
Надо:
"Внимание!!! Действие приведет к безвозвратному удалению объекта из пространства Онто, в том числе и со всех диаграмм, где он присутствует."

**Comment by SmirnovaChristina** [comment]
![Снимок экрана 2023-05-23 110443](https://github.com/hope4b/onto/assets/113026498/c19d09ef-9473-4774-a348-7b4fa9cadd2b)
Готово
