### ISSUE TITLE
Через связи на диаграмму вытаскивается не картинка

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#170]
1. На диаграмме_1 добавляем картинку_1 и связываем ее с другим элементом_1 на этой диаграмме_1.
2. Открываем другую диаграмму_2
3. Через поиск находим и добавляем на диаграмму_2 элемент_1
4. Выделяем элемент_1, на сайдбаре находим в связях картинку_1 и перетаскиваем ее на диаграмму_2
5. Видим, что вместо картинки_1 на диаграмму_2 добавился стикер с названием картинки_1

https://user-images.githubusercontent.com/94846908/223194760-23b4e88e-0892-482b-94d2-7653389e51d1.mov

**Comment by vamukhin** [comment]
нужна доработка бэка

**Comment by rosalieuru** [comment]
fixed
