### ISSUE TITLE
Выравнивание окон диаграмм

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#171]
При внесении имени диаграммы окно увеличивается (удлиняется) или уменьшается в зависимости от длины имени.
![Снимок экрана 2023-03-13 115524](https://user-images.githubusercontent.com/113026498/224653296-d0777d30-48f1-41a0-a5ea-6ac4aa9433d0.png)

**Comment by rosalieuru** [comment]
пофиксили
