### ISSUE TITLE
Выбор связи на диаграмме

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#172]
Есть три варианта отображения связи на диаграмме
1. Макеты линий:
![photo_2023-03-13_20-00-52](https://user-images.githubusercontent.com/94846908/224772474-ee7e344b-e6cf-41eb-96ce-5669b84b3b68.jpg)
1.1. Связь - тип линии для отображения связи между двумя элементами на диаграмме.
1.2. Промежуточное состояние - тип линии, когда над линией или рядом с ней находится курсор.
1.3. Выбранная - тип линии, когда ее выбрали одну (либо в будущем попала в группу выделенных элементов).
2. Точки привязки 
2.1. Сейчас точки привязки связей постоянно отображаются. 
2.2. Для линии в промежуточном состоянии, заливку точки привязки с белого цвета поменять на цвет линии в промежуточном состоянии 0D99FF.
![2023-03-13_18-57-19](https://user-images.githubusercontent.com/94846908/224774618-e54e8061-30b1-420e-adc5-022516478383.png)
2.3. Для линии в Выбранном состоянии.
2.3.1. Размер точки привязки увеличить в 1,5 раза.
2.3.2. Заливку точек привязки с белого цвета поменять на цвет 0D99FF.
3. При выборе линии - открывается сайдбар, при закрытии сайдбара выделение с линии снимается.
4. Увеличить зону активации Промежуточного состоянии линии.
4.1. Как на рисунке, все что внутри красного прямоугольника - область выделения линии. Граница прямоугольника не учитывается.
![2023-03-13_20-24-47](https://user-images.githubusercontent.com/94846908/224780229-75a2afeb-d2d0-410b-88f9-2cbcf20eb2be.png)
4.2. Область выделения линии не масштабируется при увеличении или уменьшении общего масштаба диаграммы.
![2023-03-13_20-34-44](https://user-images.githubusercontent.com/94846908/224782511-1deb909f-30d1-4cc1-924b-fdbfd67a9738.png)

**Comment by vamukhin** [comment]
1.2 Нужно однозначно понять что значит рядом. Прицеливание здесь это основная проблема для юзера. Нужно, чтобы этот функционал и было полезен и не мешал при максимальном и минимальном зумах

**Comment by vamukhin** [comment]
Какую проблему решает пункт 2, зачем это делать?

**Comment by vamukhin** [comment]
Ну это ещё нужно как-то доказать, а у нас проект ещё не достиг этапа развития, где нужно а б тесты проводить

**Comment by AndreyDobrichenko** [comment]
Вид стрелок переработан, точки привязки убрали
![image](https://user-images.githubusercontent.com/94846908/230342472-373dd81b-06fa-40a1-a109-4e58357a181e.png)
