### ISSUE TITLE
Не восстанавливается тип связи между объектами из сайдбара "Связи" 

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#173]
Воспроизвести 

1. найти объект у которого есть типизированная связь в карточке объекта

![image_2023-03-14_15-38-17](https://user-images.githubusercontent.com/47814520/225005662-35c8b4e0-e717-4642-bab7-2012c05339ef.png)

на диаграмму вынести эти оба объекта

![image_2023-03-14_15-38-17 (2)](https://user-images.githubusercontent.com/47814520/225005699-e4bbf7c9-b059-40c3-80a9-3907bd823b49.png)

в сайдбаре "Связи" воспользоваться функцией восстановления связи

![image_2023-03-14_15-38-17 (3)](https://user-images.githubusercontent.com/47814520/225005737-7c079ec6-da36-40e1-81e9-09390e1e4fae.png)

**Comment by AndreyDobrichenko** [comment]
Похожа на задачу https://github.com/hope4b/onto/issues/154

**Comment by AndreyDobrichenko** [comment]
Заработало
