### ISSUE TITLE
По разному сортируются свойства

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#178]
Редактор объекты
Внесение списка полей (свойства объекта)

При внесении свойств, порядок их отражения в карточке и в сайдбаре на диаграмме будет разный.

С чем связано?
![Снимок экрана 2023-03-16 194252](https://user-images.githubusercontent.com/113026498/225691709-048cf7f6-9685-4fdb-bbed-824f35423e06.png)

**Comment by rosalieuru** [comment]
Принято решение сделать для свойств фиксированную сортировку по А-Я

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/171

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/177
