### ISSUE TITLE
Не загружается визуальное представление отображения для пользователя

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#18]
![image](https://user-images.githubusercontent.com/47814520/146335718-e869831c-486c-4a72-9d45-9bbf7ec8cd3c.png)

**Comment by AndreyDobrichenko** [comment]
:authority: ontonet.online
:method: GET
:path: /api/v2/core/realm/06ac694c-1a18-45ae-9e83-cc1d84be2d7a/layout/user/bcfc10f8-146b-4f8e-a1c0-3d766400ba11
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: ru,en;q=0.9
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Img0VnBWN294RURFUTNpNmtuekdSOSJ9.eyJpc3MiOiJodHRwczovL2Rldi13cmt2dHY3by51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTc1Mzg5NDc1MDkwMDgzMjgwMjkiLCJhdWQiOlsiaHR0cHM6Ly9vbnRvLWNvcmUvYXV0aC9hcGkiLCJodHRwczovL2Rldi13cmt2dHY3by51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjM5NjQzNDgxLCJleHAiOjE2Mzk3Mjk4ODEsImF6cCI6InlRV3BPMDdXWll4Y3JERmpvVzhrbzFxcGR5aVpTeElKIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTplbnRpdHkiLCJkZWxldGU6bWV0YSIsInJlYWQ6bm9kZXMiLCJ1cHNlcnQ6ZW50aXR5IiwidXBzZXJ0Om1ldGEiXX0.TxUNIzZJRF0Tv5jd9kO2Famub22AmoX0JAvHzxc7s4JC9xMIDM69eSKrM8OjJ6KrjLSy1tI6Uw2Bm9JSBpSD7nNHIKQH8ma49NYRMs_8eQjpttlX6Uxz1qpeEfxlu3QWCd-uFVuLjSAHE9rLwmtO6-Ci0NCHKMiGJKWl61HckOqSpgeGJmK3WBxKI1BYYqynacqcZ8EIcZoNXcxj7_Oi8m7rGC56igSMUK_adMMdgMt4OfdFnU56dtNN4qYcrtkxsUBgFBQEja5aJDheQYQ5jL9k4ylYTxgi1gVdsp1oXKQwoO40SJFrA7fipZGOcgbCgX05uGjLR1RIhd_SDoygnQ
cookie: SLO_GWPT_Show_Hide_tmp=1; SLO_wptGlobTipTmp=1; _legacy_auth0.yQWpO07WZYxcrDFjoW8ko1qpdyiZSxIJ.is.authenticated=true; auth0.yQWpO07WZYxcrDFjoW8ko1qpdyiZSxIJ.is.authenticated=true
referer: https://ontonet.online/ru/home
sec-ch-ua: "Chromium";v="94", "Yandex";v="21", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sentry-trace: 7facca7b45704493bf8491712d32b132-95752427e721364a-1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.3.940 Yowser/2.5 Safari/537.36

**Comment by hope4b** [comment]
![image](https://user-images.githubusercontent.com/47814520/146336437-170c558f-6003-4f2d-8ff9-0093626c3e18.png)

**Comment by AndreyDobrichenko** [comment]
:authority: ontonet.online
:method: GET
:path: /api/v2/core/user/current
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: ru,en;q=0.9
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Img0VnBWN294RURFUTNpNmtuekdSOSJ9.eyJpc3MiOiJodHRwczovL2Rldi13cmt2dHY3by51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTc1Mzg5NDc1MDkwMDgzMjgwMjkiLCJhdWQiOlsiaHR0cHM6Ly9vbnRvLWNvcmUvYXV0aC9hcGkiLCJodHRwczovL2Rldi13cmt2dHY3by51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjM5NjQ1NTk1LCJleHAiOjE2Mzk3MzE5OTUsImF6cCI6InlRV3BPMDdXWll4Y3JERmpvVzhrbzFxcGR5aVpTeElKIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTplbnRpdHkiLCJkZWxldGU6bWV0YSIsInJlYWQ6bm9kZXMiLCJ1cHNlcnQ6ZW50aXR5IiwidXBzZXJ0Om1ldGEiXX0.ePHCxmSSEuiaK--OIyzCe1nTc1nEQNnP6JVcj1BTT4LLSzooGcbgJ059TDYUpPfYdFKTbMShPqenr5B0zDQ5jWN2TLnAio7I62R76dUEXgjgUchpvEVDKq2TKj0GtiPup_vRNrwwo2_dyi0elXG4oS5X4T3qbfMjBraIIRyg9Pyw2jCs5oQm3GWrvuMeNsn9mw_oLpQqCyHf8rt6YAxbq9Ou4_3u7QukoGX5XRNx-swyazrwsgRFcdJznwC-wY9ugDre5pL6QWiMefcMj5vbTNUPo3v0Lqnz88ZMDDcUnbM_vIc8brbyYwWlJQrD1PJRYzY92lNQKdsy0ls4vTEzOg
cookie: SLO_GWPT_Show_Hide_tmp=1; SLO_wptGlobTipTmp=1; _legacy_auth0.yQWpO07WZYxcrDFjoW8ko1qpdyiZSxIJ.is.authenticated=true; auth0.yQWpO07WZYxcrDFjoW8ko1qpdyiZSxIJ.is.authenticated=true
referer: https://ontonet.online/ru/home
sec-ch-ua: "Chromium";v="94", "Yandex";v="21", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 YaBrowser/21.11.3.940 Yowser/2.5 Safari/537.36

**Comment by AndreyDobrichenko** [comment]
Response:
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-type: application/json
date: Thu, 16 Dec 2021 09:06:36 GMT
expires: 0
pragma: no-cache
server: nginx/1.17.1
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
wtf-test-header: works
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block

**Comment by hope4b** [comment]
![image](https://user-images.githubusercontent.com/47814520/146350084-91bb2bf8-bf84-409b-a049-46d8ec7eec59.png)

**Comment by AndreyDobrichenko** [comment]
старая
