### ISSUE TITLE
Диаграмма / Цвет сбрасывается при открытом сайдбаре

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#180]
Если не закрыть сайдбар не переключаться на другие элементы и обновить диаграмму, то выбранный в палитре цвет сбросится на цвет по умолчанию.

https://user-images.githubusercontent.com/94846908/225858679-d177e88d-3f56-4538-918e-b992fb7f3ec4.mov

**Comment by vamukhin** [comment]
предсказуемое поведение

**Comment by rosalieuru** [comment]
"Ограничивается бэком"

**Comment by Kibnet** [comment]
А что тут собственно происходит? Описания не достаточно.

**Comment by AndreyDobrichenko** [comment]
выбираешь стикер, открывается сайдбар, устанавливаешь новый цвет стикеру, видишь что на диаграмме цвет стикера изменился на новый - ожидаешь, что цвет у стикера изменился, но если не закрывая сайдбара обновить страницу, то новый цвет стикера не сохраняется

**Comment by rosalieuru** [comment]
не воспроизводится
