### ISSUE TITLE
Открытый сайдбар мешает

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#181]
1. Не сохраняется изменение цвета
2. Не сохраняется применение шаблона к стикеру
3. Не сохраняется очищение шаблона у объекта (должен стать стикером)
4. Не сохраняется замена шаблона у объекта

**Comment by rosalieuru** [comment]
Непонятны условия, нужно больше информации или видео. У меня воспроизвести не удалось.

**Comment by SmirnovaChristina** [comment]
1. при открытом сайдбаре не возможно скрыть элемент

**Comment by SmirnovaChristina** [comment]
2. https://github.com/hope4b/onto/issues/220

**Comment by SmirnovaChristina** [comment]
3. https://github.com/hope4b/onto/issues/219

**Comment by SmirnovaChristina** [comment]
4. https://github.com/hope4b/onto/issues/180
