### ISSUE TITLE
Сайдбар. Очистка (сброс) шаблона у объекта -> цвет у объекта остается шаблонный

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#182]
1. есть объект с шаблонным цветом
2. Очищаем шаблон
3. у объекта на диаграмме остается шаблонный цвет, а должен быть цвет стикера по умолчанию

https://user-images.githubusercontent.com/94846908/225869578-1ba85a85-222f-404c-a6b8-d19ca5b38ad3.mov

**Comment by vamukhin** [comment]
предсказуемое поведение.

Я установил цвет стикеру
Поставил стикеру шаблон со своим цветом
Убрал класс со стикера
Какого должен быть цвета стикер? почему дефолтный, если я устанавливал ему цвет ранее?

пока оставляем так, на фронте сейчас я не могу определить откуда взялся цвет. От класса или был установлен отображению вручную

**Comment by AndreyDobrichenko** [comment]
Кейс немного другой. Цвет стикеру ручками не устанавливается. Т.е. стикер был с дефолтным цветом, к нему применили шаблон с цветом, затем удаляем шаблон - ожидаем, что стикер станет с дефолтным цветом, а не останется с цветом шаблона.
