### ISSUE TITLE
Диаграмма. Старый цвет из шаблона не сбросился

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#184]
Объект имел цвет_1 из шаблона_1, к нему применяется шаблон_2 без цвета.
Ожидаемое поведение. К объекту применяется шаблон_2, цвет объекта становится по умолчанию (желтым).
Баг. Обновление диаграммы приводит к закреплению иконки_2 и цвету_1 (должно быть иконка_2, цвет по умолчанию (желтый).

https://user-images.githubusercontent.com/94846908/225876162-6e62896f-4465-4d91-87c5-d4db9f08f73f.mov

**Comment by vamukhin** [comment]
с цветом то же самое, что и здесь
https://github.com/hope4b/onto/issues/182

иконка исправилась после обновления бэка

**Comment by AndreyDobrichenko** [comment]
У объекта был шаблонный цвет (мы не выставляли его ручками, он подтянулся из шаблона), меняем шаблон - ожидаем что у объекта цвет подтянется из нового шаблона (в этом конкретном случае в новом шаблоне цвет не выбран). В результате цвет у объекта остался от первого шаблона, что не правильно.
