### ISSUE TITLE
Диаграмма / Точки привязки при удалении шаблона в карточке объекта

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#185]
У объекта на диаграмме имеющего шаблон_1 и шаблонный цвет_1 удалили шаблон_1 в карточке объекта.
Ожидаемое поведение. Объект превращается в стикер с цветом по умолчанию (желтым).
Баг. Реальное поведение. Ничего не происходит. Если обновить диаграмму, то объект теряет иконку и цвет из шаблона, но визуально остается объектом. 
**При этом если объект выделить, то на сайдбаре видно, что у него нет шаблона, а точки привязки стрелок смещаются так, как будто это стикер.** 
Если снять выделение с объекта, точки привязки стрелок как к объекту. Если изменить текст объекта, то при закрытии сайдбара, объект становится стикером. Либо нажать очистить шаблона на сайдбаре.

https://user-images.githubusercontent.com/94846908/225883477-ff1d8c5e-ec96-4f8a-b26d-2d465c614683.mov

**Comment by hope4b** [comment]
Само изменение норм, но в целом ситуация неправильная. Удалять шаблон у которого есть экземпляры нельзя. Передаю задачу Кристине для доработки. Леша должен запретить делать такие штуки )

**Comment by AndreyDobrichenko** [comment]
Не против концепции "не удалять родительскую сущность, пока есть дочернии", у нас сейчас так с удалением объекта работает.
Тогда в Редакторе, у нас должна быть возможность удалить у объекта шаблон (или из шаблона удалить объект).

**Comment by rosalieuru** [comment]
Добавлено ограничение на удаление шаблона, у которого есть экземпляры
