### ISSUE TITLE
Групповые изменения на диаграмме

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#188]
1. Переработка перемещения по диаграмме. Двигать диаграмму лево/право/вверх/низ по зажатию правой кнопки мыши. 
2. Выделение нескольких элементов на диаграмме.
2.1. Выделение рамкой (секущая рама). Возможные альтернативные варианты: охватывающая рама (выделяются только те объекты, которые целиком попадают в зону выделения), лассо. Вариант как в автокад, слева на право - секущая рама, справа на лево - охватывающая рама. 
2.1.1. Если зажать левую кнопку мыши на пустом месте на диаграмме и начать ее перемещать, от начальной точки до текущего положения курсора отрисовывается прямогольная область с явной границей и фоном. 
**Нужен макет**

https://user-images.githubusercontent.com/94846908/226105842-7bd38add-9bca-4709-8a4c-060d5e54ca51.mov

2.1.2. По периметру всех элементов (кроме связей), которые частично или полностью попадают в прямоугольную область в процессе выделения - появляется рамка, визуально подсказывающая, какие элементы выберутся после отжатия левой кнопки мыши.
**Нужен макет**

https://user-images.githubusercontent.com/94846908/226105937-60429be8-ccf1-4591-91b0-8cfb0fc62663.mov

2.1.3. Если отжать левую кнопку мыши, все попавшие под выделение элементы (см. п. 2.1.2) - остаются выделенными, отрисовывается прямоугольник по крайним элементам попавшим в выделение. 
**Нужен макет**

https://user-images.githubusercontent.com/94846908/226105735-8576a47e-c815-4c36-8dff-75a78c03286e.mov

2.2. Выделение с SHIFT.
2.2.1. При зажатой клавише SHIFT, если кликать по элементам на диаграмме - они становятся выделенными.
2.2.2. Вокруг выделенных элементов отрисовывается прямоугольник, как в п.2.1.3.

https://user-images.githubusercontent.com/94846908/226106160-38043cec-e0d9-4fe0-9bad-ebb05f38fd4d.mov

2.2.3. Если есть несколько выделенных элементов, зажать клавишу SHIFT и кликнуть по выделенному элементу - выделение с такого элемента снимается.

https://user-images.githubusercontent.com/94846908/226106505-dab984de-f0cb-4fb9-9f73-8259119bae36.mov

2.2.4. Курсор мыши меняется при попадании в прямоугольную зону ограничивающую группу выделенных элементов.
**Нужен макет курсора**

https://user-images.githubusercontent.com/94846908/226107163-264d2308-26a0-4664-b058-1c76cbd3f838.mov

3. К выделенным элементам можно применить групповые изменения. 
3.1. Перемещение группы элементов.
3.1.1. Я могу передвинуть группу элементов зажатой левой кнопкой мыши. Когда курсор попадает в прямоугольную зону группы элементов, зажатие левой кнопки мыши и перемещение курсора перемещает все выделенные элементы.
3.1.1.1. Для начала перемещения курсору достаточно находится внутри прямоугольной зоны, не обязательно размещать курсор над одним из выделенных элементов.
3.1.1.2. Если внутри прямоугольной зоны группы выделенных элементов есть элемент без выделения, то над таким элементом курсор меняет свой вид на обычный.
3.1.1.3. Если нажать левую кнопку мыши внутри прямоугольной зоны группы элементов, когда курсор находится над элеметом без выделения, то все выделение сбрасывается и выделяется один элемент, над которым был курсор.
3.1.2. Отжатие левой кнопки мыши фиксирует новое положение группы элементов. При этом элементы остаются выделенными.

https://user-images.githubusercontent.com/94846908/226107711-2bd44a98-772a-4cda-97dd-c2877f8e287a.mov

3.1.2. Я могу передвинуть группу элементов стрелками на клавиатуре. Есть группа выделенных элементов, нажатие стрелок на клавиатуре перемещает группу элементов в соответствующую сторону.

https://user-images.githubusercontent.com/94846908/226107898-59267698-3214-4802-98df-17d66434c071.mov

3.2. Удаление (скрытие) группы элементов.
3.2.1. Клавишей DEL или Backspace. Есть группа выделенных элементов, нажатие клавиш DEL или Backspace приводит к удалению (скрытию) этих элементов с диаграммы.
3.2.2. Инструментом "Скрыть с диаграммы". 
3.2.2.1. Если есть группа выделенных элементов и выбрать инструмент "Скрыть с диаграммы" - на углах прямоугольника группы выделенных элементов появляются индикаторы удаления, как у отдельных элементов. 
**Нужен макет**
3.2.2.2. Если кликнуть внутри прямоугольной зоны группы элементов при активированном инструменте "Скрыть с диаграммы" - все элементы группы удалятся (скроются).
3.2.2.3. Если внутри прямоугольной зоны группы, был не выделенный элемент и при активированном инструменте "Скрыть с диаграммы" кликнуть по нему, то удалится только этот элемент. Выделение группы остается.
3.3. Удаление шаблона у всех элементов группы.
3.4. Назначение шаблона всем элементам группы.
3.5. Изменение цвета всем элементам группы.
3.6. Сброс цвета у всех элементов группы на цвет по умолчанию (либо шаблонный, если у элемента есть шаблон).
3.7. Выравнивание элементов группы, в линию по вертикали, в линию по горизонтали, прямоугольником.
3.8. Добавить свойство всем элементам группы.
3.9. Изменить комментарий всем элементам группы. Добавить/удалить.
3.10. Добавить/удалить-скрыть связь от элементов группы к какому нибудь элементу.
3.11. Скопировать выделенные элементы.
3.12. Вставить скопированные элементы, в том числе и на другой диаграмме.
4. Сайдбар группы элементов.
**Нужен макет сайдбара группы элементов.**
4.1. В поле Имя - текст "Группа элементов"?
4.2. Задать цвет - без изменений?
4.3. Комментарий - заблокировано?
4.4. Задать шаблон - без изменений?
4.5. Свойства?
4.6. Под свойствами - перечисление всех элементов группы?

**Comment by SmirnovaChristina** [comment]
Описание перенесено в раздел Вики: https://github.com/hope4b/onto/wiki/Групповые-изменения-на-диаграмме
