### ISSUE TITLE
Диаграмма. Одновременный сдвиг нескольких объектов

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#190]
1. Выделение путем выделения области диаграммы. Все объекты целиком попавшие в эту область должны быть включены в группу для последующей работы
2. работу сокета update/representation/coordinates сделать пакетной

сейчас
        realmId: this.realmsStorage.currentRealmId.value,
        diagramId: this.diagramDataStorage.getValue().id,
        userId: this.userStorage.user.value.id,
        updateCoordinatesRequest: {
          representationId: id,
          coordinates: {
            x,
            y,
          },
        },

сделать
        realmId: this.realmsStorage.currentRealmId.value,
        diagramId: this.diagramDataStorage.getValue().id,
        userId: this.userStorage.user.value.id,
        updateCoordinatesRequest: [{
          representationId: id,
          coordinates: {
            x,
            y,
          },
        }],

**Comment by hope4b** [comment]
выделение объектов описаны в https://github.com/hope4b/onto/issues/188

2.1.2. По периметру всех элементов (кроме связей), которые частично или полностью попадают в прямоугольную область в процессе выделения - появляется рамка, визуально подсказывающая, какие элементы выберутся после отжатия левой кнопки мыши.

**Comment by hope4b** [comment]
реализуем так : выделение прямоугольником левой кнопкой с зажатым шифтом. При перемещении одного объекта перемещаются все выделенные. прямоугольник не остается

**Comment by SmirnovaChristina** [comment]
Описание перенесено в Вики: https://github.com/hope4b/onto/wiki/Групповые-изменения-на-диаграмме
См. задачу #188
