### ISSUE TITLE
Изменение текста связи -> пропадание отображения

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#191]
1. Находимся на диаграмме, где есть две и более связей.
2. Выбираем связь, изменяем текст.
3. Кликаем на другую связь.
4. Связь для которой меняли текст пропадает.

https://user-images.githubusercontent.com/94846908/226556462-31d3e180-c77e-40bc-924a-228f24759715.mov

**Comment by rosalieuru** [comment]
Пофиксили
