### ISSUE TITLE
Диаграмма / Место под комментарий на объекте остается, после удаления комментария

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#192]
Объект не адаптируется по размеру после удаления комментария.

**Шаги для воспроизведения:**
1. Создать новый объект на диаграмме
2. Открыть сайдбар объекта
3. Задать любой шаблон
4. Добавить большой комментарий, например из 75 символов
5. Закрыть сайдбар
6. Нажать кнопку развертывания на объекте
7. Открыть сайдбар объекта
8. Удалить комментарий
9. Закрыть сайдбар

**Ожидаемый результат:** объект возвращается в исходный размер, кнопка развертывания исчезает
**Фактический результат:** объект остается такого же размера с пустым местом комментария, кнопка развертывания исчезает

**Воспроизводимость**: всегда
**Приоритет:** нормальный
**Серьезность:** незначительный
Комментарий: если объект свернуть перед удалением комментария, то размер остается исходным

https://user-images.githubusercontent.com/94846908/227724754-99974343-321d-4d4a-95aa-0c8b013e88f9.mov

**Comment by rosalieuru** [comment]
неактуально с релизом нового представления
