### ISSUE TITLE
Очень долго загружается список диаграмм

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#193]
URL-адрес запроса: https://ontonet.online/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa3/diagram/v2/page/1/size/1000

![image](https://user-images.githubusercontent.com/47814520/228041030-96c15432-3569-446f-ba79-1319379e1eab.png)

**Comment by rosalieuru** [comment]
fixed
