### ISSUE TITLE
При удалении полей шаблона в редакторе шаблонов, у объекта на диаграмме не удаляются свойства - заданные через поле шаблона 

### ISSUE THREAD

**Issue by AlexanderShaleins** [hope4b/onto#195]
Заходим в редактор шаблона - выбираем шаблон переходим в карточку объекта - создаем поле шаблона - переходим в экземпляры - задаем параметры полей шаблона - у объекта на диаграмме появляются заданные атрибуты - переходим обратно к карточке шаблона - удаляем поле шаблона - у объекта на диаграмме не пропадают удаленные атрибуты - придется удалять в ручную у каждого объекта  
![Screenshot (1)](https://user-images.githubusercontent.com/105632547/228575461-b07dc6d8-f19b-4703-b66e-003f325cd695.png)
![Screenshot (2)](https://user-images.githubusercontent.com/105632547/228579574-d354e8a9-1a19-4fa5-a6e2-c56fcddf663f.png)
![Screenshot (3)](https://user-images.githubusercontent.com/105632547/228585826-e01124c4-fa02-43e8-ac2c-335af91770c9.png)
![Screenshot (4)](https://user-images.githubusercontent.com/105632547/228585914-1e762e48-6347-4624-8b33-16ae5deab07a.png)

**Comment by rosalieuru** [comment]
Удаление поля в шаблоне не удаляет поле в свойствах стикера.
Из-за этого например на диаграмме "Спринт разработка" если кликнуть на объект с именем, то в свойствах стикера будет много дублирующийся информации (скрин)

**Шаги для воспроизведения:**
1. Создать новый шаблон с наименованием "Тест 196"
2. Добавить новое поле в шаблон с наименованием  "Поле 1"
3. На диаграмме создать новый стикер 
4. Задать стикеру шаблон "Тест 196"
5. Перейти в Редактор шаблонов
6. Выбрать из списка шаблон "Тест 196" 
7. Перейти во вкладку "Экземпляры" 
8. В столбце "Поле 1" ввести любое валидное значение, например "1"
9. Вернуться на диаграмму к созданному стикеру "Новый объект" и проверить, что новое поле свойства отобразилось
10. Открыть Редактор шаблонов, перейти к шаблону "Тест 196" 
11. Во вкладке "Шаблон" удалить "Поле 1" 
12. Добавить новое поле с наименованием "Поле 2"
13. Во вкладке "Экземпляры" в столбце "Поле 2" ввести любое валидное значение, например "2"
14. Вернуться на диаграмму к нашему стикеру "Новый объект" 
15. Проверить поле свойств у стикера 

**Фактический результат:** в поле свойств стикера отображается и "Поле 1" и "Поле 2"
**Ожидаемый результат:** в поле свойств стикера отображается "Поле 2"


**Воспроизводимость**: всегда
**Приоритет:** высокий
**Серьезность:** высокий

![fields dub](https://user-images.githubusercontent.com/129202997/228889101-2ac44a5e-5bf5-41a1-a388-4ddabef7fca5.png)

**Comment by vamukhin** [comment]
больше похоже на фичу, а не на баг. Сначала нужно проговорить еще раз концепцию онто и точно определиться, что это баг. Если это баг, то задача на бэк

**Comment by hope4b** [comment]
Свойства и не должны удаляться. Должны удалиться привязки к шаблонному полю. Эта задача на бекенд
