### ISSUE TITLE
При создании нового реалма нельзя отказаться от его создания 

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#2]

**Comment by AndreyDobrichenko** [comment]
При нажатии кнопки "Cancel" ничего не происходит.
![image](https://user-images.githubusercontent.com/94846908/143232191-f5a7201f-bbb0-4417-a3ee-cb32d7534086.png)

**Comment by AndreyDobrichenko** [comment]
При нажатии ESC или кнопки "х" добавляется пустой серый кружок, который пропадает если обновить страницу.
![image](https://user-images.githubusercontent.com/94846908/143232760-3f134c44-8669-41d0-8552-e7cfe466b33f.png)

**Comment by AndreyDobrichenko** [comment]
актуально

**Comment by AndreyDobrichenko** [comment]
не актуально
