### ISSUE TITLE
Непонятный указатель после создания объекта

### ISSUE THREAD

**Issue by IvanKhar** [hope4b/onto#20]
Еще кстати моментик такой появился после рефакторинга: когда добавляешь новый объект, то у меня указатель остается в виде пальца, что не очень понятно для пользователя, что с ним делать дальше

**Comment by AndreyDobrichenko** [comment]
Может изменить курсор "Указательный палец" на другой, более похожий на добавление объекта?

**Comment by AndreyDobrichenko** [comment]
не актуально, инструмент работает так, что после добавления одного объекта можно добавить следующий
