### ISSUE TITLE
Форма регистрации / отсутствует проверка валидности введенного e-mail

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#201]
Поле e-mail при регистрации принимает любые значения на латинице при наличии хотя бы одного символа до и после @

**Шаги для воспроизведения:**
1. Перейти на ontonet.online
2. Нажать "Регистрация в системе" внизу формы авторизации
3. Ввести в поле e-mail 1@1 или test@test
4. Ввести любой пароль
5. Нажать "Продолжить"

**Фактический результат:** регистрация успешно завершается
**Ожидаемый результат**: регистрация не завершается, появляется всплывающее сообщение о неправильно введенном e-mail

**Воспроизводимость:** всегда
**Приоритет**: средний
**Серьезность**: высокий

**Комментарий:** можно решить верификацией через письмо на почту, или добавить другие обязательные условия кроме наличия @

https://user-images.githubusercontent.com/129202997/230307293-49a19b84-8875-46c9-80b3-e4b9465e4bd7.mp4

**Comment by hope4b** [comment]
93cb0bc0 Artem Varkulevich <artem.varkulevich@gmail.com> on 27.04.2023 at 17:56

добавил сообщение об ошибке
