### ISSUE TITLE
Окно авторизации с квадратиком

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#202]
В разных браузерах по разному выглядит элемент Продолжить с Google
Яндекс Браузер Версия 23.3.1.806 (64-bit)
![image](https://user-images.githubusercontent.com/94846908/230393737-67da93e4-968b-4b9f-94e7-e830ede6afbe.png)
Google Chrome Версия 112.0.5615.50 (Официальная сборка), (64 бит)
![image_2023-04-06_16-28-32](https://user-images.githubusercontent.com/94846908/230393819-0b13104e-31da-4108-8f73-dfdebab5e0b9.png)

**Comment by AndreyDobrichenko** [comment]
https://user-images.githubusercontent.com/94846908/230397051-c48f9282-a66d-48d0-9215-9dc501559edd.mov

**Comment by rosalieuru** [comment]
У кого отображалась рамка - пропадала в режиме инкогнито. Условия воспроизведения до сих пор неизвестны. Будут условия - откроем.
