### ISSUE TITLE
Диаграмма. Вставка картинки из буфера не работает

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#207]
На диаграмме не работает вставка изображения из буфера обмена 

**Шаги к воспроизведению:**
1. Скопировать любое изображение 
2. Открыть диаграмму
3. Попробовать вставить изображение на диаграмму через ctrl+v и меню правой кнопки мыши

**Фактический результат:** изображение не появляется на диаграмме
**Ожидаемый результат:** изображение появляется  на диаграмме

**Воспроизводимость:** всегда
**Приоритет:** высокий
**Серьезность:** средний

Комментарий: возможность "вставить" отсутствует в меню правой кнопки мыши 

https://user-images.githubusercontent.com/129202997/230623642-6c537f05-b78e-4a56-91a8-25eb48ccd69a.mp4

**Comment by hope4b** [comment]
Работает, но надо что бы фокус был на диаграмме. Сначала надо нажать кнопкой мыши на диаграмму, после этого провести вставку Ctrl-V

**Comment by rosalieuru** [comment]
С функциональной точки зрения - работает. 
Изображения вставляются хаотично. 
Понравится ли конечному пользователю как работает вставка - сомневаюсь.

Рекомендация: привлечь аналитика для того чтобы продумать и прописать алгоритм и требования, и реализовать функцию с дружелюбным для пользователя поведением. Например: вставка изображения по местоположению курсора

**Comment by hope4b** [comment]
Владу на анализ. Картинки вставляются при фокусе на диаграмме
