### ISSUE TITLE
Диаграмма. Вставка списка из буфера не работает

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#208]
На диаграмме не работает вставка списка из буфера обмена

**Шаги к воспроизведению:**

1. Скопировать несколько строк их Excel таблицы 
2. Открыть диаграмму
3. Попробовать вставить список на диаграмму через ctrl+v и меню правой кнопки мыши

**Фактический результат:** список не появляется как объект на диаграмме
**Ожидаемый результат:** список появляется как объект на диаграмме

**Воспроизводимость:** всегда
**Приоритет:** высокий
**Серьезность:** средний

Комментарий; без видео, так как процесс тот же, что и при вставке изображения в #207

**Comment by rosalieuru** [comment]
Работает раз через три. а то и реже (даже при условии фокуса на диаграмму). Иногда срабатывает если добавить новый стикер и удалить. 

Из того, что получилось вставить из буфера: 
1. Текстовые документы: маркированные, нумерованные, немаркированные и ненумерованные списки. Вставляются в формате строка = стикер.
2. Таблицы; вставляется только 1 колонка, в формате ячейка=стикер. При вставке из Excel также вставляется изображение выделенной области.
