### ISSUE TITLE
Диаграмма / Не видно комментария у вытащенного на диаграмму объекта, сразу.

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#210]
1. В базе есть объект с комментарием.
2. На диаграмме, ищем объект в базе, вытаскиваем на диаграмму.
3. **Баг**. Не видим на диаграмме, что у объекта есть комментарий, в сайдбаре комментарий видим.
4. Обновляем диаграмму, видим что у объекта есть комментарий.

https://user-images.githubusercontent.com/94846908/231468454-ede423f1-8dd1-43f6-b6e2-53e0bc699e5c.mov

**Comment by vamukhin** [comment]
коммент с бэка не приходит

https://ontonet.online/api/v2/core/realm/{realmId}/diagram/v2/${diagramId}/all_nodes/filtered?

**Comment by vadimmpog** [comment]
![image](https://github.com/hope4b/onto/assets/56549802/c1557fbd-b87f-4cab-9e73-0365f6175f14)

Добавил комментарий в ответе метода, требуется доработка фронта
https://github.com/hope4b/a4b-core/pull/490
