### ISSUE TITLE
Пространство / Модальное окно с обучением скрывается только до конца сессии

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#213]
При отметке чекбокса "Больше не показывать" в модальном окне с обучением, окно пропадает только до конца сессии

**Шаги к воспроизведению:**
1. Авторизоваться в Ontonet.online 
2. На модальном окне отметить "больше не показывать"
3. Закрыть модальное окно

**Фактический результат:** модальное окно снова появляется через некоторое время  
**Ожидаемый результат:** модальное больше не появляется

Воспроизводимость: всегда
Приоритет: низкий
Серьезность; низкий

Комментарий: из-за короткого срока жизни куки на сокрытие модального окна оно появляется снова и снова

**Comment by Cracer00** [comment]
Исправил, привёл в соответствии с макетом

**Comment by rosalieuru** [comment]
пока решили продлив срок жизни куки
