### ISSUE TITLE
Пространство / вертикальные скроллы пересекают нижнюю границу хедера 

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#214]
Между нижней границей хедера и скроллами нет отступа 

**Шаги для воспроизведения:**
1. Создать 1 диаграмму
2. Вернуться в пространство
2. Создать 8 пространств
3. Найти скроллы в правом верхнем углу 

**Воспроизводимость:** всегда 
**Приоритет:** низкий
**Серьезность:** низкий 

Комментарий: не соответствует фигме

![image](https://user-images.githubusercontent.com/129202997/232753994-54c6059b-a26e-46c1-8c22-a0996f1e6b32.png)

**Comment by Cracer00** [comment]
Исправил, привёл в соответствии с макетом
