### ISSUE TITLE
Пространство / список пространств не выравнен по отношению к кнопке аккаунта

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#216]
Блок с кнопками пространств не выравнен по центру относительно кнопки аккаунта

**Шаги для воспроизведения:**
1. Открыть пространство
2. Найти блок с пространствами в правой части экрана

**Фактический результат:** кнопки пространств смещены влево от кнопки аккаунта
**Ожидаемый результат:** кнопки пространств центрированы по вертикали по кнопке аккаунта

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий

Комментарий; не соответствует фигме

![image](https://user-images.githubusercontent.com/129202997/232767214-faa8f6e1-2976-4f47-80a4-fcd6b6018545.png)

**Comment by Cracer00** [comment]
Починил
