### ISSUE TITLE
Пространство / внутренний отступ карточки диаграммы некликабелен

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#225]
Область внутреннего отступа карточки диаграммы не активна при наведении и некликабельна

**Шаги для воспроизведения:**
1. Открыть пространство
2. Навести курсор на край карточки диаграммы

Фактический результат: область внутреннего отступа карточки неактивна и некликабельна
Ожидаемый результат: вся область карточки диаграммы активна и кликабельна 

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий

**Комментарий:** по верхней границе карточки неактивная область больше, чем значение отступа, возможно наложение с другим элементом, нужно смотреть

https://user-images.githubusercontent.com/129202997/233978280-ccec2aa8-b9ed-4c4a-a542-975b8ab2582b.mp4

![padding inactive](https://user-images.githubusercontent.com/129202997/233974216-b517168b-b72b-4f5e-a5e5-7322c874e0f8.png)

**Comment by Cracer00** [comment]
Исправлено)
