### ISSUE TITLE
Связь не поспевает за объектом

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#23]
Если изменить описание объекта (больше или меньше букв в названии), то визуальное отображение связи не перемещается за изменившимся размером объекта. Расположение связи переопределяется при перемещении объектов.

https://user-images.githubusercontent.com/94846908/146730839-a5001c4f-d22d-4f80-8a14-e38f148b9e3a.mp4

**Comment by hope4b** [comment]
Надо обсудить. Может быть это фича?

**Comment by AndreyDobrichenko** [comment]
не актуально
