### ISSUE TITLE
Диаграмма / ошибка при вводе определенных спецсимволов в поле поиска среди объектов 

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#230]
? * + ( [ ] { )
Поиск не работает при введении этих спецсимволов в поле, возвращается "Ошибка загрузки нод" "Internal Server Error" status: 500

**Шаги для воспроизведения:**
1. Открыть диаграмму
2. Создать стикер с наименованием "?"
3. Закрыть сайдбар стикера
4. Открыть сайдбар поиска
5. в поле поиска ввести "?"

**Фактический результат:** результат поиска не выводится, поле результата уходит в анимацию загрузки
**Ожидаемый результат:** выводится результат поиска с объектом с наименованием "?"

**Воспроизводимость**: всегда
**Приоритет:** средний
**Серьезность:** средний

Комментарий: при вводе обеих круглых скобок в формате ( объект ) поиск работает корректно почему-то

![image](https://user-images.githubusercontent.com/129202997/235869959-5ff5f4f5-c805-4363-89ca-dc91e56eedf5.png)
![image](https://user-images.githubusercontent.com/129202997/235870067-2eab12b9-b9ee-4217-b63e-1f364122a26e.png)

**Comment by vadimmpog** [comment]
https://github.com/hope4b/a4b-core/pull/491
Также решает 231, 232, 244
