### ISSUE TITLE
Диаграмма / некорректный результат поиска при вводе определенных спецсимволов в поле поиска среди объектов

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#231]
^ | \ . $ 
При поиске среди объектов с использованием этих спецсимволов результатом выводится просто полный список объектов без фильтрации

**Шаги для воспроизведения:**
1. Открыть диаграмму
2. Создать стикер с наименованием " \ объект"
3. Закрыть сайдбар объекта
4. Открыть сайдбар поиска
5. Ввести в поле поиска "\ объект"

**Фактический результат:** в поле результата выводится список объектов не соответствующих запросу 
**Ожидаемый результат:** в поле результата выводится объект с наименованием " \ объект"

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

Комментарий: на символ $ воспроизводится только при отсутствии других в поле, если ввести $ + слово, то поиск просто не дает результат 

![image](https://user-images.githubusercontent.com/129202997/235930111-67a439d2-20fc-43c1-af92-5a2ddd8758c5.png)

**Comment by SmirnovaChristina** [comment]
https://github.com/hope4b/a4b-core/pull/491
