### ISSUE TITLE
Диаграмма / не работает поиск среди объектов при использовании некоторых спецсимволов в формате слово+слово

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#232]
^ | \ . $ ? * + ( [ ] { )
Поиск не выдает результатов при использовании этих спецсимволов в формате слово + слово

**Шаги для воспроизведения:**
1. Открыть диаграмму
2. Создать стикер с наименованием "объект + объект"
3. Закрыть сайдбар стикера
4. Открыть сайдбар поиска
5. В поле поиска ввести "объект + объект"

**Фактический результат:** высвечивается надпись "элементы не найдены"
**Ожидаемый результат:** выводится результат поиска с объектом с наименованием "объект + объект"

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

![image](https://user-images.githubusercontent.com/129202997/235936554-ddb5e0ff-a68c-4c3f-9930-3e833c20b085.png)

**Comment by SmirnovaChristina** [comment]
https://github.com/hope4b/a4b-core/pull/491
