### ISSUE TITLE
Совместная работа / 500 ошибка с бэка при переходе на диаграмму по ссылке, находясь в другом пространстве 

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#236]
При попытке открыть диаграмму по ссылке находясь в другом пространстве - окно уходит в бесконечную загрузку, бэк возвращает internal server error
Нет автоматического переключения на пространство, которое содержит диаграмму по ссылке.

**Предусловие:** 2 аккаунта на ontonet.online (A и B)
**Шаги для воспроизведения:**
1. Зайти в аккаунт А 
2. Создать диаграмму с названием "Диаграмма 1"
3. Вернуться на страницу пространства 
4. Нажать кнопку "Пригласить" 
5. Скопировать ссылку нажав "Пригласить" в модальном окне
6. Зайти в аккаунт B 
7. Вставить ссылку в адресную строку
8. Перейти по ссылке
9. Принять приглашение в пространство 
10. Обновить страницу и убедиться, что пространство А появилось
11. Убедиться, что активно пространство B
12. Перейти в аккаунт А
13. Зайти в диаграмму "Диаграмма 1"
14. Скопировать ссылку из адресной строки
15. Перейти в аккаунт B
16. Вставить ссылку на диаграмму в адресную строку
17. Перейти по ссылке

**Фактический результат:** "Диаграмма 1" не открывается, окно уходит в бесконечную загрузку
**Ожидаемый результат:** открывается "Диаграмма 1"

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

Комментарий:
 {
    "timestamp": "2023-05-10T13:33:41.379+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/api/core/realm/454809bc-c6b8-40d0-8547-6c1808178ae3/diagram/v2/c17da161-51ba-4282-882b-f1db75850cf7"
}

![image](https://github.com/hope4b/onto/assets/129202997/028240c5-e632-41a7-be9b-590494c253e6)

**Comment by SmirnovaChristina** [comment]
[16.06
](https://t.me/c/1952648056/699/3709)
