### ISSUE TITLE
Диаграмма / объект окрашивается в черный при применении шаблона с дефолтным цветом

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#242]
После перезагрузки страницы шаблон с дефолтным цветом не применяется корректно на диаграмме, где уже есть хотя бы 1 объект с этим шаблоном 

**Шаги для воспроизведения:**
1. Перейти в Редактор
2. Создать новый шаблон с наименованием "Шаблон без цвета"
3. Перейти на диаграмму 
4. Создать новый стикер
5. Назначить созданному стикеру шаблон "Шаблон без цвета"
6. Закрыть сайдбар
7. Подождать 10 секунд
8. Обновить страницу 
9. Создать новый стикер 
10. Назначить созданному стикеру шаблон "Шаблон без цвета"

**Фактический результат:** стикер меняет форму на объект, объект отображается с черной заливкой, заданный шаблон отображается некорректно
**Ожидаемый результат:** стикер меняется на объект, объект отображается с дефолтным цветом, заданный шаблон отображается корректно

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

**Комментарий:** если открыть сайдбар такого объекта, то он отображается корректно, закрыть - снова черный. После перезагрузки страницы объект начинает отображаться корректно. 

https://github.com/hope4b/onto/assets/129202997/4430b358-fb75-4162-9ecf-889e14f42c67

**Comment by vadimmpog** [comment]
https://github.com/hope4b/a4b-core/pull/485
