### ISSUE TITLE
Диаграмма / в результатах поиска не отображаются объекты и шаблоны, у которых в наименовании есть ↵ Enter

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#244]
Поиск в сайдбаре данных не отображает стикеры/объекты/шаблоны в имени которых есть ↵ Enter, независимо от его месторасположения в наименовании

**Шаги для воспроизведения:** 
1. Перейти на диаграмму
2. Создать новый стикер
3. Дать ему наименование "Перевод строки ↵ Enter"
4. Закрыть сайдбар
5. Открыть сайдбар данных
6. В поле поиска ввести "Перевод строки"

**Фактический результат:** как результат поиска выводится сообщение "Элементы не найдены"
**Ожидаемый результат:** в результате поиска отображается стикер "Перевод строки"

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

![image](https://github.com/hope4b/onto/assets/129202997/67c4ae56-929d-4a72-88cb-6361a69314c5)

**Comment by SmirnovaChristina** [comment]
https://github.com/hope4b/a4b-core/pull/491
