### ISSUE TITLE
Диаграмма / изменения шаблона не отображаются на объектах вытащенных через сайдбар 

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#249]
Цвет и иконка не меняются на объектах, которые были размещены на диаграмме через сайдбар

**Предусловие:** создать шаблон, задать любую иконку и синий цвет; создать шаблону объект и дать ему наименование "Тест сайдбара"

Шаги для воспроизведения:
1. Перейти на диаграмму
2. Открыть сайдбар поиска
3. В поле поиска ввести "Тест сайдбара"
4. Перенести объект с сайдбара на диаграмму
5. Кликнуть на объект и открыть его сайдбар
6. Перейти в редактирование шаблона
7. Сменить шаблону цвет на зеленый 
8. Сменить шаблону иконку 
9. Перейти "Назад"

**Фактический результат:** цвет и иконка на объекте остались прежними
**Ожидаемый результат:** цвет и иконка изменились на новые

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

**Comment by hope4b** [comment]
по тесткейсу работает как надо.

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/180
