### ISSUE TITLE
Сайдбар / 500 ошибка при одновременном сохранении полей с другими данными объекта

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#250]
Если одновременно внести изменения в объект и в поля (создать новые или добавить значения), то при закрытии сайдбара и попытке сохранения возникает 500 ошибка.  После этого любые изменения через сайдбар перестают сохраняться.

**Шаги для воспроизведения:**
1. Перейти на диаграмму
2. Создать стикер
3. Кликнуть на стикер и открыть его сайдбар
4. Изменить имя на "Объект 500"
5. Создать новое поле
6. Закрыть сайдбар
7. Кликнуть на стикер и снова открыть сайдбар

**Фактический результат:** в консоли возникает 500 ошибка на сохранение fields, сайдбар уходит в бесконечную загрузку
**Ожидаемый результат:** все внесенные изменения успешно сохраняются и отображаются

**Воспроизводимость:** всегда
**Приоритет:** высокий
**Серьезность:** высокий

![image](https://github.com/hope4b/onto/assets/129202997/12ddc33e-282b-492f-b03e-f2927249889b)

**Comment by vadimmpog** [comment]
https://github.com/hope4b/a4b-core/pull/484
