### ISSUE TITLE
Сайдбар / в связях по диаграммам отображаются удаленные диаграммы

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#251]
В списке диаграмм где представлен объект остаются диаграммы после удаления

Предусловие: создать две диаграммы с наименованием "Диаграмма 1" и "Диаграмма 2"

**Шаги для воспроизведения:**
1. Перейти на Диаграмму 1
2. Создать 2 стикера с наименованием "Объект 1" и "Объект 2"
3. Построить связь между созданными стикерами
4. Перейти на Диаграмму 2
5. Открыть сайдбар
6. В поле поиска ввести "Объект 2"
7. Разместить объект на диаграмме
8. Перейти на стартовую страницу пространства
9. Удалить Диаграмму 2
10. Перейти на Диаграмму 1
11. Кликнуть на Объект 2 и открыть его сайдбар
12. Перейти на вкладку Связи

Фактический результат: в разделе Диаграммы отображается Диаграмма 2
Ожидаемый результат: в разделе Диаграммы не отображается Диаграмма 2

**Воспроизводимость**: всегда
**Приоритет:** низкий
**Серьезность:** средний

**Comment by hope4b** [comment]
бекенд в сервисе related_nodes отдает удаленные диаграммы. Скорее всего они реально не удаляются, а помечаются. Надо посмотреть как это сделано в списке диаграмм

https://preprod.ontonet.ru/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa3/diagram/v2/767a3065-31bd-4f1e-87b8-f4efbd4174a4/representation/c2d7474d-af64-431c-8501-4e51ea173ccd/related_nodes

список диаграмм 
https://preprod.ontonet.ru/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa3/diagram/v2/page/1/size/1000



![image](https://github.com/hope4b/onto/assets/47814520/9f5cc698-30d1-44cb-b525-2ce760aedf40)
