### ISSUE TITLE
Пространство / во вкладке Мои диаграммы не отображаются диаграммы

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#255]
Во вкладке Мои диаграммы не отображаются ни старые ни новые диаграммы 

**Шаги для воспроизведения:**
1. Перейти в пространство
2. Создать новую диаграмму
3. Дать ей наименование Диаграмма 1
4. Перейти в пространство 
5. Перейти на вкладку Мои диаграммы

**Фактический результат:** созданная диаграмма не отображается
**Ожидаемый результат:** созданная диаграмма отображается

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность**: средний

**Comment by hope4b** [comment]
сервис не возвращает данные 
https://app.ontonet.ru/api/v2/core/realm/[REALM]/diagram/v2/my/page/1/size/1000
