### ISSUE TITLE
Отваливаются коннекторы связей 

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#26]
открыл диаграмму реалма ДРИБС

https://ontonet.online/ru/home/operation/E?uuid=b07e5028-8225-4fc2-a3eb-7dfd2da67954

использовал инструмен Show Linked на узле  "Обработка распоряжений на перечисление средств на счета ФЛ"

результат на картинке

![image](https://user-images.githubusercontent.com/47814520/147412626-0a308333-957a-42e6-9e04-323727d13301.png)

**Comment by AndreyDobrichenko** [comment]
старая
