### ISSUE TITLE
Диаграмма / не работает поиск по шаблонам в сайдбаре объекта если наименование шаблона содержит ↵ Enter в середине

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#261]
В поиске не отображаются шаблоны, в наименовании которых ↵ Enter содержится в середине

**Шаги для воспроизведения:**
1. Перейти в Редактор
2. Создать новый шаблон
3. Дать ему наименование "Шаблон ↵ Enter со строкой"
4. Перейти на диаграмму
5. Создать стикер
6. Открыть его сайдбар
7. В поле Шаблон ввести "Шаблон со строкой"

**Фактический результат:** высвечивается надпись "Пусто"
**Ожидаемый результат:** в результате поиска отображается "Шаблон со строкой"

**Воспроизводимость**: всегда
**Приоритет:** средний
**Серьезность:** средний

**Comment by vadimmpog** [comment]
https://github.com/hope4b/a4b-core/pull/552
Исправил, теперь нельзя создать шаблон с переходом строки в имени шаблона
