### ISSUE TITLE
Редактор / Объекты "Owner" и "Participant" в списке объектов пространства

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#262]
При переходе в Редактор в списке объектов отображаются системные артефакты - Owner и Participant

**Предусловие:** 2 аккаунта с пустым общим пространством
**Шаги для воспроизведения:**
1. Перейти в общее пространство 2 аккаунтов
2. Перейти в Редактор

**Фактический результат**: в табличном представлении пространства отображаются объекты Owner и Participant
**Ожидаемый результат**: табличное представление пространства пустое

**Воспроизводимость:** всегда
**Приоритет**: низкий
**Серьезность**: низкий

![image](https://github.com/hope4b/onto/assets/129202997/7662c308-8da4-4e9b-8d01-d1eb0462fe30)

**Comment by vadimmpog** [comment]
Поправил, ссылка на pr - https://github.com/hope4b/a4b-core/pull/513
