### ISSUE TITLE
Редактор / задержка при множественном назначении главного шаблона

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#263]
Долго отрабатывает запрос на множественное назначение главных шаблонов

**Предусловие:** создать 3 шаблона с полями (Шаблон 1, Шаблон 2, Шаблон 3)

**Шаги для воспроизведения:**
1. Перейти в Редактор
2. Открыть Шаблон 1
3. Перейти во вкладку Шаблон
4. В поле Главный шаблон ввести в поле "Шаблон"
5. В отобразившемся списке отметить без задержки чекбоксы слева от Шаблон 2 и Шаблон 3
6. Кликнуть в стороне и закрыть список

**Фактический результат:** поля шаблонов подгружаются ~5 сек и более
**Ожидаемый результат:** поля шаблонов подгружаются без задержки

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

**Comment by vadimmpog** [comment]
Поправил
https://github.com/hope4b/a4b-core/pull/553
