### ISSUE TITLE
Редактор / надпись на английском при поиске среди шаблонов во вкладке Объект

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#265]
При клике на поле поиска во вкладке Объект надпись отображается на английском языке

**Шаги для воспроизведения:**
1. Перейти в Редактор
2. Открыть карточку любого объекта без шаблона
3. Кликнуть на поле Шаблон

**Фактический результат**: отображается "No results found"
**Ожидаемый результат**:  отображается "Шаблоны не найдены"

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/250
