### ISSUE TITLE
Редактор / поле поиска (фильтрации) не скрывается при переходе в карточку объекта

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#267]
Если при открытом поле поиска (фильтрации) перейти в карточку объекта - поле не закрывается и продолжает отображаться

**Предусловие:** созданный объект
**Шаги для воспроизведения:**
1. Перейти в Редактор
2. В табличном представлении пространства открыть поле поиска на столбце "Имя"
3. Кликнуть на имя объекта 
4. Перейти в карточку объекта через строчное меню

**Фактический результат:** поле поиска отображается
**Ожидаемый результат:** поле поиска скрылось

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий

![image](https://github.com/hope4b/onto/assets/129202997/dd9deedd-eb19-4e69-94a9-dcb1e7a55269)

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/257
