### ISSUE TITLE
Диаграмма / null в строке комментария у объектов

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#268]
У некоторых объектов сервис связанных объектов отдает null в комментарии

**Примечание: данный баг очень сложно воспроизвести с нуля, поэтому воспроизведение будет на основе существующего объекта в пространстве Онто**

**Шаги для воспроизведения:** 
1. Перейти в пространство Онто
2. Открыть диаграмму  "00. TEST!!"
3. Найти на диаграмме объект "public-controller"
4. Кликнуть на него и открыть его сайдбар 
5. Перейти во вкладку Связи
6. В списке связанных объектов найти объект "onto-core V2"
7. Перетащить объект "onto-core V2" на диаграмму
8. Раскрыть комментарий объекта "onto-core V2"

**Фактический результат:** в комментарии объекта отображается "null"
**Ожидаемый результат:** комментарий отсутствует 

**Примечание 2:** у некоторых объектов нет null прямо в представлении, но есть в representation related nodes 

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий 

![image](https://github.com/hope4b/onto/assets/129202997/64759e1c-0ca2-421d-b505-bfd764a52c99)
![image](https://github.com/hope4b/onto/assets/129202997/0c1b18c4-1ad7-49bb-a35c-5858c6ebe514)

**Comment by vadimmpog** [comment]
https://github.com/hope4b/a4b-core/pull/527
