### ISSUE TITLE
Редактор / поиск в дереве шаблонов чувствителен к регистру 

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#270]
**Шаги для воспроизведения:**
1. Перейти в Редактор
2. Создать два шаблона с наименованиями Шаблон 1 и шаблон 1
3. В поле поиска в дереве шаблонов ввести "шаблон 1"

**Фактический результат:** в результате поиска отображается только один шаблон
**Ожидаемый результат;** в результате поиска отображается и шаблон 1 и Шаблон 1

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий

**Comment by vamukhin** [comment]
на этом этапе фронт дёргает grapql. Сделать запрос регистронезависимым не получается, тк нет подходящего селектора в запросе. Не понял как работает _match. Где то написано, что он умеет принимать регулярки, но документацию у меня найти не получилось, и отправить регулярку методом тыка не получилось тоже.

[Здесь](https://neo4j.com/docs/graphql/current/queries-aggregations/filtering/#_regex_matching) написано, что в neo4j по дефолту регулярки выключены. В коде бэка явного включения/выключения я не нашёл.

Вывыд: 
либо доработка бэкэнда
либо доработка конфигов graphql/Neo4j на бэке для отправки регулярок
либо покажите пример как всё таки отправлять регулярки  

P.S.  В доке отправлять регулярки не рекомендуют, не просто так они выключены

**Comment by hope4b** [comment]
> доработка бэкэнда
кажется что сейчас это хорошая для нас задача.
