### ISSUE TITLE
Редактор / нет логичной сортировки в табличном представлении пространства 

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#273]
**Шаги для воспроизведения:**
1. Создать Шаблон 1
2. Создать в Шаблон 1 объекты с наименованиями "1", "2", "3", "4", "5"
3. Создать Шаблон 2 
4. Создать в Шаблон 2 объекты с наименованиями "a", "b", "c", "d", "e"
5. Перейти в табличное представление пространства

**Фактический результат:** объекты отображаются без логичной сортировки
**Ожидаемый результат:** объекты отображаются с логичной сортировкой

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** средний

**Comment by vadimmpog** [comment]
Поправил, https://github.com/hope4b/a4b-core/pull/544
