### ISSUE TITLE
Диаграмма / Объекты "Owner" и "Participant" в списке объектов пространства

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#276]
При переходе на диаграмму в списке объектов в сайдбаре отображаются системные артефакты - Owner и Participant

**Предусловие:** 2 аккаунта с пустым общим пространством

**Шаги для воспроизведения:**
1. Перейти в общее пространство 2 аккаунтов
2. Создать новую диаграмму

**Фактический результат:** в сайдбаре отображаются объекты Owner и Participant
**Ожидаемый результат**: в сайдбаре нет объектов

**Воспроизводимость:** всегда
**Приоритет:** низкий
**Серьезность:** низкий

![image](https://github.com/hope4b/onto/assets/129202997/71b0d56b-e786-48a4-865d-6119c13e772c)

**Comment by vadimmpog** [comment]
Поправил, https://github.com/hope4b/a4b-core/pull/515
