### ISSUE TITLE
Редактор / при вводе "" в поле фильтрации find возвращает 400 ошибку

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#279]
**Шаги для воспроизведения:**
1. Перейти в Редактор
2. В табличном представлении пространства создать объект с названием "Объект"
3. Открыть поле фильтрации по Имени
4. Ввести "Объект" в поле фильтрации

**Фактический результат**: результата фильтрации нет, табличное представление остается прежним
**Ожидаемый результат:** в табличном представлении отображается строка с "Объект"

**Comment by vadimmpog** [comment]
Баг фронта, неправильно формируется запрос с спецсимволами
""" вместо "\""
