### ISSUE TITLE
Диаграмма / создается дубликат представления связи

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#282]
**Шаги для воспроизведения:**
1. Перейти на диаграмму и создать два стикера - Стикер 1 и Стикер 2
2. Построить связь от Стикер 1 к Стикер 2
3. Построить еще одну связь от Стикер 1 к Стикер 2

**Фактический результат:** создается связь дублирующая уже существующую 
**Ожидаемый результат:** дублирующая связь не создается 

**Воспроизводимость:** всегда
**Приоритет:** высокий
**Серьезность:** высокий

**Комментарий:** если ноунейм связь уже существует, то не создавать новую, а отдавать ее в представление

![image](https://github.com/hope4b/onto/assets/129202997/4d7fb657-1202-4f31-afff-544e004ebeee)

**Comment by vadimmpog** [comment]
Поправил
https://github.com/hope4b/a4b-core/pull/518
