### ISSUE TITLE
Диаграмма / цвет объекта  сбрасывается до дефолтного

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#285]
При назначении объекту другого цвета и сбросе до шаблонного, после перезагрузки объект отображается с дефолтным желтым цветом

Предусловие: диаграмма, шаблон с цветом

**Шаги для воспроизведения:**
1. Перейти на диаграмму
2. Создать стикер
3. Назначить стикеру шаблон с цветом
4. Назначить объекту цвет, отличный от цвета шаблона
5. Сбросить цвет объекту до шаблонного
6. Обновить страницу

**Фактический результат:** объект отображается с дефолтным (желтым цветом)
**Ожидаемый результат:** объект отображается с цветом шаблона

**Воспроизводимость:** всегда
**Приоритет:** высокий
**Серьезность:** средний

**Комментарий:** два поля цвета, бэк удаляет одно

**Comment by hope4b** [comment]
https://preprod.ontonet.ru/ru/home/operation/E?uuid=e20d3335-2b8a-4add-a13e-d1b7fccc4f3e&realm=000ba00a-00a0-0a00-a000-000a0a0a0aa3

**Comment by hope4b** [comment]
![image](https://github.com/hope4b/onto/assets/47814520/eba113a2-8d83-41d0-957e-54132cbce7ee)

**Comment by hope4b** [comment]
Ошибка воспроизводится у объектов на основе шаблонов со структурой наследования

**Comment by hope4b** [comment]
https://preprod.ontonet.ru/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa3/diagram/v2/e20d3335-2b8a-4add-a13e-d1b7fccc4f3e/representation/edbed510-b30d-4032-9cc0-e2d633e98edf/extended?diagramId=e20d3335-2b8a-4add-a13e-d1b7fccc4f3e&realmId=000ba00a-00a0-0a00-a000-000a0a0a0aa3&representationId=edbed510-b30d-4032-9cc0-e2d633e98edf

**Comment by hope4b** [comment]
![image](https://github.com/hope4b/onto/assets/47814520/3ce7240b-6526-4e45-bc77-4fe07d3c3c7f)

**Comment by hope4b** [comment]
![image](https://github.com/hope4b/onto/assets/47814520/011381b3-32a0-4b84-8a75-ca0b6747aec7)
