### ISSUE TITLE
Пространство / не отображаются новые диаграммы во вкладке "Мои диаграммы"

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#287]
**Шаги для воспроизведения:**
1. Перейти в пространство
2. Создать новую диаграмму с названием "Диаграмма 287"
3. Вернуться в пространство
4. Перейти во вкладку "Мои диаграммы"

**Фактический результат:** Диаграмма 287 не отображается в списке диаграмм
**Ожидаемый результат:** Диаграмма 287 отображается в списке диаграмм

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

**Комментарий: если диаграмма создана копированием, она также должна отображаться во вкладке "Мои диаграммы"**

**Comment by vadimmpog** [comment]
https://github.com/hope4b/a4b-core/pull/525
