### ISSUE TITLE
Диаграмма / Поиск выводит объекты в шаблоне разбивая шаблон на несколько

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#293]
Бэк отдает ограниченное количество объектов у шаблона при поиске, при прокрутке не подгружаются следующие объекты того же шаблона, а разбиваются в отдельный шаблон

**Шаги для воспроизведения:**
1. Перейти в пространство Онто
2. Открыть любую диаграмму 
3. В сайдбаре в поле поиска ввести "SMM"
4. Найти в выдаче поиска шаблон "[SMM] Задача. Сделано"
5. Прокрутить вниз до еще одного шаблона "[SMM] Задача. Сделано"

**Фактический результат:** в результатах поиска отображается два шаблона "[SMM] Задача. Сделано" с разным набором объектов
**Ожидаемый результат:** в результате поиска отображается один шаблон "[SMM] Задача. Сделано" со всеми объектами сразу

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** низкий

![image](https://github.com/hope4b/onto/assets/129202997/400807b4-a952-4137-bfcd-58a151e40e06)

**Comment by vadimmpog** [comment]
Поправил, ссылка на pr - https://github.com/hope4b/a4b-core/pull/536
