### ISSUE TITLE
Редактор / не сохраняются данные в поле при вставке через меню правой кнопки мыши

### ISSUE THREAD

**Issue by rosalieuru** [hope4b/onto#294]
В табличном представлении шаблона и пространства ни в одной из ячеек не сохраняются данные при вставке через меню правой кнопки мыши 

Предусловие: наличие шаблона с полем

**Шаги для воспроизведения:** 
1. Скопировать в буфер любое текстовое значение
2. Перейти в Редактор 
3. Перейти в табличное представление шаблона
4. Кликнуть на ячейку в столбце Имя/Комментарий/Поле шаблона
5. Открыть меню правой кнопки мыши 
6. Выбрать в меню "Вставить"
7. Снять выделение с ячейки

**Фактический результат:** данные не сохраняются
**Ожидаемый результат:** данные сохраняются 

**Воспроизводимость:** всегда
**Приоритет:** средний
**Серьезность:** средний

Комментарий: не отправляется запрос на сохранение

**Comment by hope4b** [comment]
https://github.com/hope4b/a4b-webui/pull/260
