### ISSUE TITLE
Не подтягиваются на диаграмме связи класса

### ISSUE THREAD

**Issue by Stunka** [hope4b/onto#30]
Мне необходимо вытащить все объекты класса исполнитель 
я вытащила на диаграмму класс и team_member_meta_DESCRIBER и попросила показать всех кто  с ним связан

**Comment by hope4b** [comment]
у _DESCRIBER не должно быть связей

**Comment by hope4b** [comment]
@Stunka что ты делала в итоге?

**Comment by AndreyDobrichenko** [comment]
старая
