### ISSUE TITLE
Сортировка в списке диаграмм по умолчанию по имени диаграммы

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#33]
https://ontonet.online/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa3/diagram/page/1/size/8

сейчас возвращает так, а нужно что бы по имени сортировало
`{"totalResults":15,"totalPages":2,"page":1,"size":8,"results":[{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"ba72b1a4-0396-4c2d-811d-1211885fe607","name":"01.3. Диаграмма","comment":"undefined"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"75c6d7c9-e33c-412b-bc7e-8de8fe9db51b","name":"01.3. FrontMindMap","comment":"undefined"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"430dc469-66ac-436f-bdb4-0beafc39087e","name":"# Архитектура ONTO","comment":"undefined"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"ac8ca532-ae45-42b4-b61b-54c20b8bf60c","name":"01.1. Mega Onto","comment":"Ключевая диаграмма развития"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"f417a554-c93c-4f41-8602-7e4b2260ccd7","name":"01.2. Стратегия 2022","comment":"undefined"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"b03d26bb-b0fe-43f9-ba03-e6d60fc3f9ca","name":"01.2. Стратегия 2021","comment":"undefined"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"e8c649d4-4ff6-405b-8c09-8ca2c019ce99","name":"0. Навигация и знания","comment":"undefined"},{"realmId":"000ba00a-00a0-0a00-a000-000a0a0a0aa3","id":"07c4f6df-1fc3-465f-aa28-840b80102b6e","name":"## Стратегия Онто","comment":"Общая карта глобальных целей "}]}`

**Comment by AndreyDobrichenko** [comment]
на 30 апреля 2022 сортировки по имени нет:
![image](https://user-images.githubusercontent.com/94846908/166099377-c7e6e096-d621-4986-b608-d1de0166a294.png)

**Comment by AndreyDobrichenko** [comment]
не актуальна
