### ISSUE TITLE
Не сохраняется диаграмма

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#35]
https://ontonet.online/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa2/diagram?name=New%20Diagram&comment=undefined

**Request**

`Request URL: https://ontonet.online/api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa2/diagram?name=New%20Diagram&comment=undefined
Request Method: POST
Status Code: 500 
Remote Address: 84.201.174.76:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: *
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-type: application/json
date: Wed, 09 Feb 2022 10:13:40 GMT
expires: 0
pragma: no-cache
server: nginx/1.17.1
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
:authority: ontonet.online
:method: POST
:path: /api/v2/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa2/diagram?name=New%20Diagram&comment=undefined
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Img0VnBWN294RURFUTNpNmtuekdSOSJ9.eyJpc3MiOiJodHRwczovL2Rldi13cmt2dHY3by51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTE2OTIyMTkyODU2MDczOTMxODQiLCJhdWQiOlsiaHR0cHM6Ly9vbnRvLWNvcmUvYXV0aC9hcGkiLCJodHRwczovL2Rldi13cmt2dHY3by51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNjQ0NDAxNTQ2LCJleHAiOjE2NDQ0ODc5NDYsImF6cCI6InlRV3BPMDdXWll4Y3JERmpvVzhrbzFxcGR5aVpTeElKIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImRlbGV0ZTplbnRpdHkiLCJkZWxldGU6bWV0YSIsInJlYWQ6bm9kZXMiLCJ1cHNlcnQ6ZW50aXR5IiwidXBzZXJ0Om1ldGEiXX0.qZHtoO2ixiVbwiLVquXZhvpopmY9wGrXZBPkDPR1hcx1NYUcySBF4jojxeKE_MFBYENeAIsp6Pbf7yX7jJgCZoRuvLWk2Lve20XTDRS9Y83YeYd_076h-Wxibdoi4l-6Kbmq9UvtkNGAqvIjGzOijWPPniwAM15uCfqTkHFnGSiEmOTPtitQDjR71DBrwkeZPd8XUV63-VPNKZkuEqeLU1lYQsCQqCblaLv-Ht6i2mx__3Arj0usLci-rdrvfk0Y3F65nPgDs8_WUinMXgDb-UBibjosiDFQlPkn4PdgLA3nEkWnvPBaWfZ6wN9qjNwo7GZV-q95HhOoDp3ryLJDYg
cache-control: no-cache
content-length: 263
content-type: multipart/form-data; boundary=----WebKitFormBoundaryeIhQB0QaI865g121
cookie: _legacy_auth0.yQWpO07WZYxcrDFjoW8ko1qpdyiZSxIJ.is.authenticated=true; auth0.yQWpO07WZYxcrDFjoW8ko1qpdyiZSxIJ.is.authenticated=true
origin: https://ontonet.online
pragma: no-cache
referer: https://ontonet.online/ru/home/operation/newDiagram
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.81 Safari/537.36`

**Response**

`{"timestamp":"2022-02-09T10:13:40.848+00:00","status":500,"error":"Internal Server Error","message":"","path":"/api/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa2/diagram"}`

**Comment by AndreyDobrichenko** [comment]
старая
