### ISSUE TITLE
Не изменяется картинка класса

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#36]
Данные по классу

Идентификатор Дескрайбера "uuid": "9770f7b2-2b89-4afc-bdb1-6ce2cdd69f25"

`{
	"data": {
		"metaEntity": [
			{
				"describer": {
					"name": "ONTO-Знание_DESCRIBER",
					"comment": "Generated DESCRIBER for Meta Entity with uuid: 6c43a3f2-230e-403e-8923-20be9d76ffdd.",
					"fields": [],
					"uuid": "9770f7b2-2b89-4afc-bdb1-6ce2cdd69f25"
				},
				"children": [
					{
						"name": "ONTO-Конкуренты",
						"comment": null,
						"fields": [],
						"uuid": "772aba26-a866-4ddc-a0c5-6d8a1b40d233"
					}
				],
				"name": "ONTO-Знание",
				"comment": null,
				"fields": [
					{
						"name": "LINK",
						"comment": null,
						"type": "T_STRING",
						"uuid": "4cbe7dc1-a0c2-4709-87a6-df82d7c5d786"
					}
				],
				"uuid": "6c43a3f2-230e-403e-8923-20be9d76ffdd",
				"parents": []
			}
		]
	}
}`

запрос на изменение картинки выдает вот такую ошибку
`{"timestamp":"2022-02-09T18:22:13.443+0000","status":500,"error":"Internal Server Error","message":"Node with id: [9770f7b2-2b89-4afc-bdb1-6ce2cdd69f25] does not exists.","path":"/api/core/realm/000ba00a-00a0-0a00-a000-000a0a0a0aa3/entity/9770f7b2-2b89-4afc-bdb1-6ce2cdd69f25/fields"}`

**Comment by IvanKhar** [comment]
выглядит так, что сервис отработал корректно, так как и класс и дескрайбер принадлежат реалму DRIBS(000ba00a-00a0-0a00-a000-000a0a0a0aa5) 

а у тебя в запросе ид реалма = 000ba00a-00a0-0a00-a000-000a0a0a0aa3

**Comment by IvanKhar** [comment]
<img width="888" alt="Снимок экрана 2022-02-10 в 08 46 59" src="https://user-images.githubusercontent.com/41263055/153345403-47c68668-ff21-400b-84b4-bec0e431d0a5.png">

**Comment by AndreyDobrichenko** [comment]
старая
