### ISSUE TITLE
Работа с диаграммой -  не хватает инструмента для комфортного пользования 

### ISSUE THREAD

**Issue by AlexanderShaleins** [hope4b/onto#43]
Не хватает инструмента «Стрелочка», как в фотошопе, например. Чтобы я мог спокойно таскать объекты, а не добавлять лишние объекты. 
![image](https://user-images.githubusercontent.com/105632547/168560684-abc8a938-16b1-4173-abe7-2df1495c3bc3.png)

**Comment by AndreyDobrichenko** [comment]
Если не выбирать инструмент, либо после создания необходимых объектов отжать инструмент создания - то будет работать как "Стрелочка" в фотошопе, для спокойного таскания объектов.
