### ISSUE TITLE
Окно для добавления реалмов - проблема при создании нового реалма

### ISSUE THREAD

**Issue by AlexanderShaleins** [hope4b/onto#45]
Если нажать на кнопку закрытия окна, оно не закроется и перестают работать кнопки.
![image](https://user-images.githubusercontent.com/105632547/168568583-06d431ce-1eb3-4762-a6ae-ddaf64bdad40.png)

**Comment by AndreyDobrichenko** [comment]
переработан интерфейс создания реалмов (пространств), не актуально
