### ISSUE TITLE
Текст Комментарий показывается поверх добавленного комментария, после перезахода на диаграмму.

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#46]
![image](https://user-images.githubusercontent.com/94846908/171466139-cd0f776e-e744-44f0-b524-10b4d79c8c11.png)

**Comment by AndreyDobrichenko** [comment]
![image](https://user-images.githubusercontent.com/94846908/180299330-8077b45a-a762-4a0d-9bc5-c7b7e5e0f535.png)
без изменений

**Comment by hope4b** [comment]
исправлено
