### ISSUE TITLE
Регистрация только через Google

### ISSUE THREAD

**Issue by AlexanderShaleins** [hope4b/onto#47]
Добавить возможность регистрации через логин-пароль e-mail

**Comment by AndreyDobrichenko** [comment]
на текущий момент есть такая возможность
![image](https://user-images.githubusercontent.com/94846908/180317961-d6d363fc-3706-4c5b-a3fa-04bf7c324e9a.png)


- зарегистрировал нового пользователя, указал почту (подтверждать почту не надо, письма о регистрации так-же не приходит)
- при попытке зарегистрировать еще одного пользователя на туже почту - выдает предупреждение, что такая почта уже используется

![image](https://user-images.githubusercontent.com/94846908/180317336-2ff75aaf-cf84-4ec5-9749-8ba62ebb0d08.png)
