### ISSUE TITLE
Изменение названия объекта не сразу

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#5]
Если изменить название объекта через "Show Full Card", изменения не отображаются ни на панели свойств ни на самом объекте. Новое название появляется после перезагрузки страницы браузера.

https://user-images.githubusercontent.com/94846908/143395091-c0f1282e-50ad-4019-838e-fb12c6dfda89.mp4

**Comment by hope4b** [comment]
Думаю что это надо отложить до внедрения сервиса Диаграм

**Comment by AndreyDobrichenko** [comment]
Проверить когда починится редактирование карточки объекта

**Comment by AndreyDobrichenko** [comment]
не актуально
