### ISSUE TITLE
Перевести на русский элементы интерфейса

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#55]
Окно подтверждения удаления объекта из реалма
![image](https://user-images.githubusercontent.com/94846908/174395496-ac3c2753-3adf-45ca-b858-368f5d422cd7.png)

**Comment by AndreyDobrichenko** [comment]
Редактор объектов
![image](https://user-images.githubusercontent.com/94846908/174396428-fa73e656-a468-4caf-8967-76092b2a92e5.png)

**Comment by AndreyDobrichenko** [comment]
Редактор классов
![image](https://user-images.githubusercontent.com/94846908/174396572-bcd3363f-12ac-408b-8075-b3da50ffb696.png)

**Comment by AndreyDobrichenko** [comment]
опции диаграммы
![image](https://user-images.githubusercontent.com/94846908/174397163-cda23427-7eac-41bd-946b-67016a55b5e6.png)

**Comment by AndreyDobrichenko** [comment]
Правая панель
![image](https://user-images.githubusercontent.com/94846908/174397560-203e6ddb-0668-4bfb-bf45-c751f843d548.png)

**Comment by AndreyDobrichenko** [comment]
Правая панель, закладка "Связи объекта"
![image](https://user-images.githubusercontent.com/94846908/174398023-59895451-c2d0-4a2b-8634-fca7cb99bbb8.png)

**Comment by AndreyDobrichenko** [comment]
Свойства связи
![image](https://user-images.githubusercontent.com/94846908/174398879-9e6ec693-0fa5-433a-9654-90c5b444ec1e.png)

**Comment by AndreyDobrichenko** [comment]
Правая панель, редактирование объекта
![image](https://user-images.githubusercontent.com/94846908/174402759-09bdea97-2377-4962-aacd-b4ccf39e22c4.png)

**Comment by hope4b** [comment]
> Редактор объектов ![image](https://user-images.githubusercontent.com/94846908/174396428-fa73e656-a468-4caf-8967-76092b2a92e5.png)

сделано

**Comment by hope4b** [comment]
> опции диаграммы ![image](https://user-images.githubusercontent.com/94846908/174397163-cda23427-7eac-41bd-946b-67016a55b5e6.png)

сделано

**Comment by hope4b** [comment]
> Правая панель ![image](https://user-images.githubusercontent.com/94846908/174397560-203e6ddb-0668-4bfb-bf45-c751f843d548.png)

сделано

**Comment by hope4b** [comment]
> Правая панель, закладка "Связи объекта" ![image](https://user-images.githubusercontent.com/94846908/174398023-59895451-c2d0-4a2b-8634-fca7cb99bbb8.png)

сделано

**Comment by hope4b** [comment]
Сделано
