### ISSUE TITLE
Много связей между двумя объектами

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#6]
Между двумя объектами можно создать много связей.

https://user-images.githubusercontent.com/94846908/143398440-df53c27f-7a44-46e4-891a-d8cb560f334a.mp4

**Comment by hope4b** [comment]
тут непонятно ) Давай обсудим @AndreyDobrichenko

**Comment by AndreyDobrichenko** [comment]
@hope4b 
На видео я добавляю несколько связей между двумя объектами, затем их удаляю. Если с точки зрения реализованной онтологической модели ошибки нет (множественные связи между двумя объектами поддерживаются), тогда вопрос к визуализации связей на диаграмме, их надо показывать так, что бы они не были одна поверх другой.

**Comment by AndreyDobrichenko** [comment]
актуально

**Comment by AndreyDobrichenko** [comment]
вопрос с визуализацией остался

**Comment by hope4b** [comment]
в работе

**Comment by hope4b** [comment]
сделано
