### ISSUE TITLE
Цвет объекта

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#63]
При выделении на диаграмме дефолтного стикера, на правой панели отображается некорректный цвет, который соответствует дефолтному объекту с классом.
![image](https://user-images.githubusercontent.com/94846908/181306214-5f31ca9c-1ad5-493c-ae5e-a57aa5d7b67e.png)
![image](https://user-images.githubusercontent.com/94846908/181306521-3ed78b8f-8734-4bf5-b61e-2e07aefc7ce5.png)

**Comment by vamukhin** [comment]
пофиксил
