### ISSUE TITLE
Если выбрать объект А, откроется правая панель, если удалить объект Б связанный с А, то объект Б будет продолжать отображаться на панели

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#69]
https://user-images.githubusercontent.com/94846908/183750211-3a4d7df1-7ebe-4d85-9b6c-6f33402d0885.mp4

**Comment by AndreyDobrichenko** [comment]
Должен переключатся тумблер у Объекта Б

**Comment by AndreyDobrichenko** [comment]
Тоже самое при добавлении связи с новым объектом, изменения сразу не видны на правой панели.

**Comment by hope4b** [comment]
не стал занаучивать пока. информация об объекте скрывается из правой панели при удалении объекта, создании связи
