### ISSUE TITLE
Текст ноды не видно

### ISSUE THREAD

**Issue by vamukhin** [hope4b/onto#71]
https://ontonet.online/ru/home/operation/E?uuid=1b05a4bf-4b48-44f9-b2e8-394d37018dc4&realm=9ea70e6a-65c5-4fa7-be2f-328fb58a5104

![image](https://user-images.githubusercontent.com/33781070/186663153-38ee147b-6da0-4f71-8b00-b07c2870e140.png)

**Comment by hope4b** [comment]
какой-то частный случай. @vamukhin предлагаю закрыть

**Comment by AndreyDobrichenko** [comment]
Цвет текста объекта не меняется в зависимости от цвета объекта, черный текс на черном не видно

**Comment by AndreyDobrichenko** [comment]
Если задать шаблону цвет, а затем применить к объекту, цвет текста меняется в зависимости от цвета. Если менять цвет объекту инструментом на диаграмме, цвет текста объекта всегда черный.

**Comment by AndreyDobrichenko** [comment]
исправили
