### ISSUE TITLE
Окно регистрации не соответствует Фигме

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#73]
Поле регистрации. 
Нажимая на поля приходиться искать начало ввода, то есть если ткнуть на "логин", "email", "пароль" то ни чего не произойдёт, придется потыкать несколько раз прежде чем курсор найдется.

![регистрация](https://user-images.githubusercontent.com/113026498/188866044-ed44c8d8-952b-45ee-9f98-65a4b71cfb9d.png)

**Comment by SmirnovaChristina** [comment]
Желательно сделать как при авторизации, там когда тыкаешь на "email" и "пароль", то сразу можешь начать ввод.

[Авторизация В Onto - Google Chrome 2022-09-08 09-57-44.webm](https://user-images.githubusercontent.com/113026498/189057624-5125a120-13b5-4fbc-9511-df00af7d8dc8.webm)

**Comment by hope4b** [comment]
Исправил. Закрываю пока 
![image](https://user-images.githubusercontent.com/47814520/191339779-eca92a76-359e-4b48-a830-2e0c79cf5b7d.png)
