### ISSUE TITLE
Сброс индефикационных данных

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#74]
Не возможно сбросить данные при авторизации.
При вводе неправильного email или пароля, формой предполагается сброс данных через ссылку "забыли пароль?", но при переходе по ссылке выплывает окно с формулировкой "Сброс идентификационных данных не разрешен". 
Каким образом восстановить доступ к своему пространству?
![Сброс](https://user-images.githubusercontent.com/113026498/188927194-e8f27c69-30db-4f24-a496-afea7226433c.png)

**Comment by hope4b** [comment]
Сделано, но теперь появились формы для которых нет дизайна:

* указать почту
* ввести новый пароль

![image](https://user-images.githubusercontent.com/47814520/189516047-614c47b4-81e0-4908-b4cc-259d79286f9e.png)
