### ISSUE TITLE
Графический интерфейс формы "авторизация"

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#76]
Обратите внимание на **фон**. Фон при авторизации белый, при регистрации серый.

Необходимо выровнять текст, впечатление, что съехал вправо.

Определить дистанцию между словами/предложениями:
- между "войти" и "чтобы начать исследовать свою метавселенную"; 
- между полем "пароль" и "забыли пароль";
- между "забыли пароль" и "продолжить";
- между "продолжить" и "нет учетной записи";
- между "нет учетной записи" и "зарегистрироваться";
- между "зарегистрироваться" и "продолжить с";
- между "продолжить с" и иконкой гугл.
Сейчас для глаза выглядит не очень.

Начало текста прописать либо со строчной либо с прописной буквы.

Обратите внимание на поле "пароль" при просмотре пароля (кликая на "глаз") поле начинает гулять вниз и вверх.

Цвет текста. "Забыли пароль" голубой, "зарегистрироваться" фиолетовый и голубой. "Войти" черный/синий и "продолжить" в поле выглядят иначе.
!!! В целом желательно придерживаться цветов логотипа.

Шрифт текста. Проверить какой шрифт используется в полях "E-mail", "Пароль", "Продолжить".
!!! В целом более глобальный вопрос, надо определиться с шрифтами, какие будут использоваться на сайте и платформе, иначе для глазу не комфортно как минимум. Сейчас присутствуют разные шрифты: Roboto, Arial, Calibri, Trebuchet MS.

Логотип. Как правило логотип ontonet это 4 круга разных размеров и цветов размещенных на равном или не равном удалении друг от друга, логотип на форме авторизации выглядит иначе, круги наползают друг на друга.

![Авторизация_3](https://user-images.githubusercontent.com/113026498/189098283-6fffb012-b766-4444-adcc-374cffa261c9.png)

![Логотип](https://user-images.githubusercontent.com/113026498/189098909-0c1eeec6-c922-4a7f-be1d-6a3bf6ccfcdf.png)

**Comment by hope4b** [comment]
Задача для изучения Филиппом

**Comment by SmirnovaChristina** [comment]
Загружена новая форма авторизации 04.04.2023
