### ISSUE TITLE
Удаленные объекты вернулись

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#8]
Если удалить объекты с помощью "Remove node from realm", не сохранять диаграмму, заново ее открыть или обновить F5, то удаленные объекты вернутся с подписью DELETED

https://user-images.githubusercontent.com/94846908/143417376-d3a79f28-65ce-45cd-9b79-0c8d63ae6c91.mp4

**Comment by hope4b** [comment]
Этот функционал будет исправлен когда наполнение диаграммы станет динамическим через сервис диаграмм.
