### ISSUE TITLE
Подпись поля "Комментарий" на правой панели

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#82]
1. Если начать редактировать Комментарий на правой панели, то надпись "Комментарий" перемещается выше поля и частично накладывается на поле "Новый объект".
2. Если что нибудь добавить в поле Комментарий и переключиться на другой объект, то надпись "Комментарий" у другого объекта будет выше поля.
3. Надпись "Комментарий" будет выше поля, до тех пор пока не удалить у какого нибудь объекта комментарий либо не перезайти на диаграмму.
![image](https://user-images.githubusercontent.com/94846908/192358134-90ce14c8-3030-4f43-b37c-fc84fe8c4e61.png)
![image](https://user-images.githubusercontent.com/94846908/192358193-0b113aa4-82f7-4df5-b192-b11e1017141b.png)
![image](https://user-images.githubusercontent.com/94846908/192358269-eaa13941-318a-4e59-9caf-d251f82923ec.png)

**Comment by hope4b** [comment]
не актуально
