### ISSUE TITLE
Поправить отображение длинных названий стикеров и объектов

### ISSUE THREAD

**Issue by AndreyDobrichenko** [hope4b/onto#87]
Длинное название отображается не с начала текста и не целиком
![image](https://user-images.githubusercontent.com/94846908/193902849-372f96eb-90f5-4eb4-919e-0cb367abdda4.png)
![image](https://user-images.githubusercontent.com/94846908/193903034-509942c8-7f84-4ef0-b891-b7114caa343c.png)

Как минимум начинать название с начала, отображаем сколько помещается.
Как вариант добавить скрол.

**Comment by hope4b** [comment]
![image](https://user-images.githubusercontent.com/47814520/200190171-633f3469-26db-45b4-804d-31d1721e9881.png)


7ee9983f Artem Varkulevich <artem.varkulevich@gmail.com> on 06.11.2022 at 22:09
