### ISSUE TITLE
Ошибка одновременного изменения Имени, комментария и цвета объекта

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#90]
![image](https://user-images.githubusercontent.com/47814520/194078540-8841bf15-c2b9-4814-9840-51c5e7b3be22.png)

<div class="shadow-split-widget-contents shadow-split-widget-main vbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column; z-index: 50; contain: size style; flex: 1 1 auto; color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="widget vbox" slot="insertion-point-main" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important;"><div class="widget vbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style; display: flex; flex-direction: column !important;"><div class="data-grid no-selection" tabindex="0" role="application" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; line-height: 14.4px; border: none; flex: 1 1 auto;"><div class="data-container" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: absolute; inset: 0px; overflow: hidden overlay; transform: translateZ(0px); background-color: var(--color-background);">

["SEND\ndestination:/onto/diagram/v2/change/update/representation/coordinates\ncontent-length:296\n\n{\"realmId\":\"000ba00a-00a0-0a00-a000-000a0a0a0aa3\",\"diagramId\":\"767a3065-31bd-4f1e-87b8-f4efbd4174a4\",\"userId\":\"a1f77190-1834-4d8c-872d-6f9e7ab4826f\",\"updateCoordinatesRequest\":{\"representationId\":\"e25efc8e-8e78-44ea-b073-4b7e3bc737f0\",\"coordinates\":{\"x\":1233.232748824677,\"y\":1532.090902712164}}}\u0000"] | 429 | 16:55:35.636 |  
-- | -- | -- | --
a["MESSAGE\ndestination:/onto/diagram/v2/event/updated/representation/coordinates\ncontent-type:application/json\nsubscription:sub-9\nmessage-id:icz1btec-8371\ncontent-length:323\n\n{\"userId\":\"a1f77190-1834-4d8c-872d-6f9e7ab4826f\",\"realmId\":\"000ba00a-00a0-0a00-a000-000a0a0a0aa3\",\"diagramId\":\"767a3065-31bd-4f1e-87b8-f4efbd4174a4\",\"response\":{\"representationCoordinates\":{\"representationId\":\"e25efc8e-8e78-44ea-b073-4b7e3bc737f0\",\"coordinates\":{\"x\":1233.232748824677,\"y\":1532.090902712164}}},\"error\":null}\u0000"] | 541 | 16:55:36.269 |  
["SEND\ndestination:/onto/diagram/v2/change/update/node_of_representation\ncontent-length:355\n\n{\"realmId\":\"000ba00a-00a0-0a00-a000-000a0a0a0aa3\",\"diagramId\":\"767a3065-31bd-4f1e-87b8-f4efbd4174a4\",\"userId\":\"a1f77190-1834-4d8c-872d-6f9e7ab4826f\",\"representationId\":\"e25efc8e-8e78-44ea-b073-4b7e3bc737f0\",\"updateOntoNodeRequest\":{\"name\":\"05.1 Архитектура!!!\",\"comment\":\"sadsadsadsadsad\",\"metaEntityId\":\"30d4be92-cb37-4c35-bf9c-71fe7ac92304\"}}\u0000"] | 479 | 16:55:48.835 |  
["SEND\ndestination:/onto/diagram/v2/change/update/representation/color\ncontent-length:248\n\n{\"realmId\":\"000ba00a-00a0-0a00-a000-000a0a0a0aa3\",\"diagramId\":\"767a3065-31bd-4f1e-87b8-f4efbd4174a4\",\"userId\":\"a1f77190-1834-4d8c-872d-6f9e7ab4826f\",\"updateColorRequest\":{\"representationId\":\"e25efc8e-8e78-44ea-b073-4b7e3bc737f0\",\"color\":\"#6cd8fa\"}}\u0000"] | 373 | 16:55:48.836 |  
a["MESSAGE\ndestination:/onto/diagram/v2/event/updated/representation/color\ncontent-type:application/json\nsubscription:sub-10\nmessage-id:icz1btec-8375\ncontent-length:285\n\n{\"userId\":\"a1f77190-1834-4d8c-872d-6f9e7ab4826f\",\"realmId\":\"000ba00a-00a0-0a00-a000-000a0a0a0aa3\",\"diagramId\":\"767a3065-31bd-4f1e-87b8-f4efbd4174a4\",\"response\":{\"representationColor\":{\"representationId\":\"e25efc8e-8e78-44ea-b073-4b7e3bc737f0\",\"color\":{\"color\":\"#6cd8fa\"}}},\"error\":null}\u0000"] | 498 | 16:55:50.403 |  
a["MESSAGE\ndestination:/onto/diagram/v2/event/updated/representation\ncontent-type:application/json\nsubscription:sub-2\nmessage-id:icz1btec-8378\ncontent-length:298\n\n{\"userId\":\"a1f77190-1834-4d8c-872d-6f9e7ab4826f\",\"realmId\":\"000ba00a-00a0-0a00-a000-000a0a0a0aa3\",\"diagramId\":\"767a3065-31bd-4f1e-87b8-f4efbd4174a4\",\"response\":null,\"error\":{\"errorOccurred\":true,\"reason\":\"Что-то пошло не так. Пожалуйста, попробуйте снова.\"}}\u0000"] | 458 | 16:55:50.586 |  
  |   |   |  

</div><div class="data-grid-resizer" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: absolute; top: 0px; bottom: 0px; width: 5px; z-index: 500; cursor: col-resize; left: 1124px;"></div><div class="data-grid-resizer" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: absolute; top: 0px; bottom: 0px; width: 5px; z-index: 500; cursor: col-resize; left: 1188px;"></div></div></div></div></div><div class="shadow-split-widget-contents shadow-split-widget-sidebar vbox" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; position: relative; flex-direction: column; contain: size style; flex: 0 0 157px; border-right: 0px; border-bottom: 0px; border-left: 0px; border-image: initial; border-top: 1px solid var(--color-details-hairline); color: rgb(255, 255, 255); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><slot name="insertion-point-sidebar" style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="widget vbox empty-view-scroller" slot="insertion-point-sidebar" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: layout style; display: flex; flex-direction: column !important; justify-content: center; overflow: auto;"><div class="empty-view" style="box-sizing: border-box; min-width: 70px; min-height: 0px; color: var(--color-text-secondary); padding: 30px; text-align: center;"><br class="Apple-interchange-newline">

**Comment by SmirnovaChristina** [comment]
Не актуально
