### ISSUE TITLE
При изменении типа представления со стикера на объект или назад связи объекта не изменяются

### ISSUE THREAD

**Issue by hope4b** [hope4b/onto#91]
![image](https://user-images.githubusercontent.com/47814520/194079204-5cccfa20-11f7-4bb8-8d10-cc708dc815e4.png)
![image](https://user-images.githubusercontent.com/47814520/194079280-04b8c2eb-a673-40ac-8b02-3e6986e1b369.png)

**Comment by AndreyDobrichenko** [comment]
не актуально

https://user-images.githubusercontent.com/94846908/222457267-18150302-7b9b-47fc-8380-94e0514a6d8f.mov
