### ISSUE TITLE
Графические иконки

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#92]
На стартовой странице платформы есть разделы: новая диаграмма, объекты, шаблоны.
Иконки есть у объекта и шаблона, а диаграмма пустая.
Может стоит добавить графику?
![Иконки](https://user-images.githubusercontent.com/113026498/194229257-d3c8bba2-3867-4209-a242-1f3c233be993.png)

**Comment by hope4b** [comment]
поговори с Филиппом.

**Comment by SmirnovaChristina** [comment]
Время от времени напоминаю. Жду Филиппа
