### ISSUE TITLE
Hotkey (A,S,D)

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#93]
На странице диаграммы есть быстрые клавиши. 
A - добавить объект
S - добавить связь
D - удалить объект
По факту:
A не отвечает
S отправляет на сохранение страницы
![Hotkey S](https://user-images.githubusercontent.com/113026498/194230865-ccf3c9d9-8873-431e-ba68-8df138a9d340.png)
D отправляет на сохранение страницы в закладки
![Hotkey D](https://user-images.githubusercontent.com/113026498/194230889-0fa1f2b9-e923-4fc8-8152-bc590bd37e17.png)
Проверила: chrome, vivaldi, bravo, edge, mozilla, opera.

**Comment by hope4b** [comment]
@SmirnovaChristina перепроверь. мне кажется что у тебя запал ctrl

**Comment by SmirnovaChristina** [comment]
Работает
