### ISSUE TITLE
Автоматическое переключение к пространству к которому предоставили доступ (почтовые приложения)

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#94]
На стартовой странице платформы есть клавиша "пригласить", которая даёт возможность скопировать ссылку платформы пользователя.
![Пригласить](https://user-images.githubusercontent.com/113026498/194232513-7893b783-345b-4dfe-9cb9-4053c258303a.png)
Ссылка рабочая, но пользователь получивший ссылку не может открыть пространство.
Ссылка "Принять" не работает.
![Предоставление доступа](https://user-images.githubusercontent.com/113026498/194232228-ba7dc8bc-6dbf-4cc2-a257-2b5ba487fa8c.png)

**Comment by hope4b** [comment]
Вроде работает. Пространство появляется. Надо подумать про автоматическое переключение наверное

**Comment by SmirnovaChristina** [comment]
Загружено
