### ISSUE TITLE
Работа с созданием пространств

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#96]
1. Допустим, что у пользователя пространств больше чем может вместить экран, то он не может их пролистать, так как нет "бегунка"
![Меню справа_бегунок](https://user-images.githubusercontent.com/113026498/194257926-c21fc32a-915a-4ce4-b76b-0a569f5f6ca6.png)
3. А как удалить пространство?

**Comment by hope4b** [comment]
Надо поработать с Филиппом на этот счет

**Comment by hope4b** [comment]
в фигме есть кнопки скрола

![image](https://user-images.githubusercontent.com/47814520/203649009-e92fcaad-fcdd-42ef-8fee-0d9bb99a58df.png)

**Comment by SmirnovaChristina** [comment]
В работе у Влада 21.02

**Comment by SmirnovaChristina** [comment]
28.02 правая панель переработана. Появился бегунок и попап логин.
