### ISSUE TITLE
Курсор

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#97]
При создании пространства выплывает окно в котором нужно дать имя новому пространству. Но для того чтобы это сделать нужно отдельно установить курсор в поле, это снижает время работы, да и вообще отвлекает.
Можно ли установить курсор таким образом чтобы он был в поле когда выплыло окно?
![Курсор](https://user-images.githubusercontent.com/113026498/194263662-6c848fda-6671-4f8c-b6d7-99b34b4dd924.png)

**Comment by hope4b** [comment]
9f512e83 Artem Varkulevich <artem.varkulevich@gmail.com> on 04.11.2022 at 15:15
