### ISSUE TITLE
плейхолдер "новый объект"

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#98]
Плейхолдер "Новый объект"
1. Открыть диаграмму
2. Добавить объект
3. Дать имя новому объекту
Справа появляется новое окно для внесения информации по новому объекту.
Поле "Новый объект" не даёт внести сразу название объекта, то есть сначала пользователю **нужно навести курсор**, потом **удалить "новый объект"** и уже затем внести название.
Сложно и долго.
Возможно ли наименования поля "Новый объект" сделать плейхолдером?
Вот как ниже поле "Комментарий", то есть тык на "новый объект" и данное название уходит вверх давая возможность внести название.
![пЛЕЙХОЛДЕР](https://user-images.githubusercontent.com/113026498/194870023-ba9c98ab-dfbb-43f3-a383-7287b0e642c5.png)

**Comment by hope4b** [comment]
Испарвлено
