### ISSUE TITLE
Графика создания нового объекта в диаграмме

### ISSUE THREAD

**Issue by SmirnovaChristina** [hope4b/onto#99]
1. Добавить диаграмму
2. Добавить "Новый объект"
3. Кликнуть на "Новый объект"
Всплывает справа окно/карточка

- желательно выровнять поля:
выбор цветового решения я бы перенесла за поле "Новый объект";
поле "Имя/значение" придвинуть и выровнять по полям "Комментарий" и "Шаблон";
поле "Тип" придвинуть и выровнять по полям "Комментарий" и "Шаблон".
- Почему поле "Шаблон" имеет в себе восклицательный знак?
- Что такое карточка объекта? Насколько она должна выделяться на общей картине? Возможно стоит её выделить иначе не понятно надо кликнуть на неё или должна быть информация о карточке объекта под ней.
- Что такое поле "Имя/значение"? 
Как я поняла это некая табличка под "Именем" пользователь выбирает "Тип", а под "Значением" пользователь прописывает некий "Комметарий".
В этом случае, это не корректное отображение, во-первых желательно сделать выбр внесения информации непосредственно в самом "Имя" и "Значение", во-вторых почему поле именуется "Тип" если сверху это называется "Имя" и в-третьих как догадаться пользователю, что под "Значение" есть поле для внесения, потому как графика для него не предусмотрена.
![Графика название объекта](https://user-images.githubusercontent.com/113026498/194869729-29ac49b9-0799-45c4-bd90-7b9780ccd77c.png)
- Поле "Тип" выдаёт информацию на английском языке.
![Английский](https://user-images.githubusercontent.com/113026498/194869667-37197397-4275-4188-89cc-32ac677e9b22.png)
- Плейхолдер "Комментарий" смещается вверх и не корректно зависает.
![Комментарий повис](https://user-images.githubusercontent.com/113026498/194869237-14d2787b-30b3-4b70-ad2c-7890fa1e909a.png)
- Плейхолдер "Новый объект" не работает, если это поле должно быть как плейхолдер. Писала в issue №31
![пЛЕЙХОЛДЕР](https://user-images.githubusercontent.com/113026498/194869597-04210538-e9a9-46c8-9d97-1916d9a4c503.png)

**Comment by hope4b** [comment]
неактуально. Привели в соответствие фигме.
